CREATE TABLE SOCIO(
DNI VARCHAR2(9) NOT NULL,
NOMBRE VARCHAR2(50) NOT NULL,
DIRECCION VARCHAR2(100),
TELEFONO NUMBER(9),
AVALADOR VARCHAR2(9),
CONSTRAINT PK_SOCIO PRIMARY KEY (DNI),
CONSTRAINT FK_SOCIO FOREIGN KEY (AVALADOR) REFERENCES SOCIO(DNI)
);

CREATE TABLE DIRECTOR(
NOMBRE VARCHAR2(50) NOT NULL,
NACIONALIDAD VARCHAR2(30),
CONSTRAINT PK_DIRECTOR PRIMARY KEY (NOMBRE)
);

CREATE TABLE ACTORES(
NOMBRE VARCHAR2(50) NOT NULL,
NACIONALIDAD VARCHAR2(30),
SEXO VARCHAR2(1),
CONSTRAINT PK_ACTORES PRIMARY KEY (NOMBRE),
CONSTRAINT CHK_SEXO CHECK (SEXO IN ('H','M'))
);

CREATE TABLE PELICULA(
ID NUMBER(15) NOT NULL,
TITULO VARCHAR2(100) NOT NULL,
PRODUCTORA VARCHAR2(50),
NACIONALIDAD VARCHAR2(30),
FECHA DATE,
DIRECTOR VARCHAR2(50),
CONSTRAINT PK_PELICULA PRIMARY KEY (ID),
CONSTRAINT FK_PELICULA FOREIGN KEY (DIRECTOR) REFERENCES DIRECTOR(NOMBRE)
);

CREATE TABLE EJEMPLAR(
ID_PELI NUMBER(15),
NUMERO NUMBER(15),
ESTADO VARCHAR2(20),
CONSTRAINT PK_EJEMPLAR PRIMARY KEY (ID_PELI, NUMERO),
CONSTRAINT FK_EJEMPLAR FOREIGN KEY (ID_PELI) REFERENCES PELICULA(ID)
);

CREATE TABLE ACTUA(
ACTOR VARCHAR2(50) NOT NULL,
ID_PELI NUMBER(15) NOT NULL,
PROTA VARCHAR2(1) DEFAULT 'N',
CONSTRAINT PK_ACTUA PRIMARY KEY (ACTOR, ID_PELI),
CONSTRAINT FK_ACTUA FOREIGN KEY (ACTOR) REFERENCES ACTORES(NOMBRE),
CONSTRAINT FK2_ACTUA FOREIGN KEY (ID_PELI) REFERENCES PELICULA(ID),
CONSTRAINT CHK_PROTA CHECK (PROTA IN ('S','N'))
);

CREATE TABLE ALQUILA(
DNI VARCHAR2(9),
ID_PELI NUMBER(15),
NUMERO NUMBER(15),
FECHA_ALQUILER DATE NOT NULL,
FECHA_DEVOLUCION DATE,
CONSTRAINT PK_ALQUILA PRIMARY KEY (DNI, ID_PELI, NUMERO, FECHA_ALQUILER),
CONSTRAINT FK_ALQUILA FOREIGN KEY (DNI) REFERENCES SOCIO(DNI),
CONSTRAINT FK2_ALQUILA FOREIGN KEY (ID_PELI, NUMERO) REFERENCES EJEMPLAR(ID_PELI, NUMERO)
);