CREATE TABLE REGION
(
    CODREGION VARCHAR2(10),
    NOMBRE VARCHAR2(100),
    CONSTRAINT PK_REGION PRIMARY KEY (CODREGION)
);

CREATE TABLE PROVINCIA
(
    CODPROVINCIA VARCHAR2(10),
    NOMBRE VARCHAR2(100),
    CODREGION VARCHAR2(10),
    CONSTRAINT PK_PROVINCIA PRIMARY KEY (CODPROVINCIA),
    CONSTRAINT FK1_PROVINCIA FOREIGN KEY (CODREGION)
        REFERENCES REGION(CODREGION)
);

CREATE TABLE LOCALIDAD
(
    CODLOCALIDAD VARCHAR2(10),
    NOMBRE VARCHAR2(100),
    CODPROVINCIA VARCHAR2(10),
    CONSTRAINT PK_LOCALIDAD PRIMARY KEY (CODLOCALIDAD),
    CONSTRAINT FK1_LOCALIDAD FOREIGN KEY (CODPROVINCIA)
        REFERENCES PROVINCIA(CODPROVINCIA)
);

CREATE TABLE EMPLEADO
(
    ID VARCHAR2(10),
    DNI VARCHAR2(10),
    NOMBRE VARCHAR2(100),
    FECHANAC DATE,
    TELEFONO VARCHAR2(20),
    SALARIO NUMBER(10, 2),
    CODLOCALIDAD VARCHAR2(10),
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (ID),
    CONSTRAINT UQ1_EMPLEADO_DNI UNIQUE (DNI),
    CONSTRAINT FK1_EMPLEADO FOREIGN KEY (CODLOCALIDAD)
        REFERENCES LOCALIDAD(CODLOCALIDAD)
);