CREATE TABLE CLIENTE(
    NUM_CLIENTE NUMBER (10),
    SALDO NUMBER (10),
    LIM_CREDITO NUMBER (10),
    DESCUENTO NUMBER (10)
);

CREATE TABLE DIRECCION(
    COD_DIRECCION NUMBER (10),
    VIA VARCHAR2 (20),
    NOMBRE_VIA VARCHAR2 (20),
    NUMERO NUMBER (10),
    PISO NUMBER (10),
    PORTAL NUMBER (10),
    COD_POSTAL NUMBER (10)
);

CREATE TABLE POSEE(
    NUM_CLIENTE NUMBER (10),
    COD_DIRECCION NUMBER (10)
);

CREATE TABLE PEDIDO(
    NUM_PEDIDO NUMBER (10),
    FECHA DATE,
    NUM_CLIENTE NUMBER (10),
    COD_DIRECCION NUMBER (10)
);

CREATE TABLE ARTICULO(
    NUM_ARTICULO NUMBER (10),
    DESCRIPCION VARCHAR2 (40)
);

CREATE TABLE INCLUYE(
    NUM_PEDIDO NUMBER (10),
    NUM_ARTICULO NUMBER (10),
    CANTIDAD NUMBER (10)
);

CREATE TABLE FABRICA(
    NUM_FABRICA NUMBER (10),
    TELEFONO NUMBER (9)
);

CREATE TABLE DISTRIBUYE(
    NUM_ARTICULO NUMBER (10),
    NUM_FABRICA NUMBER (10),
    CANT_SUMINISTRO NUMBER (10),
    EXISTENCIAS NUMBER (10)
);


ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (NUM_CLIENTE);
CREATE SEQUENCE SEC_NUMCLIENTE START WITH 1 INCREMENT BY 1 MAXVALUE 99999999999 MINVALUE 1;

ALTER TABLE DIRECCION ADD CONSTRAINT PK_DIRECCION PRIMARY KEY (COD_DIRECCION);

ALTER TABLE POSEE ADD CONSTRAINT PK_POSEE PRIMARY KEY (NUM_CLIENTE,COD_DIRECCION);
ALTER TABLE POSEE ADD CONSTRAINT FK_POSEE FOREIGN KEY (NUM_CLIENTE) REFERENCES CLIENTE (NUM_CLIENTE);
ALTER TABLE POSEE ADD CONSTRAINT FK2_POSEE FOREIGN KEY (COD_DIRECCION) REFERENCES DIRECCION (COD_DIRECCION);

ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUM_PEDIDO);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO FOREIGN KEY (NUM_CLIENTE) REFERENCES CLIENTE (NUM_CLIENTE);
ALTER TABLE PEDIDO ADD CONSTRAINT FK2_PEDIDO FOREIGN KEY (COD_DIRECCION) REFERENCES DIRECCION (COD_DIRECCION);

ALTER TABLE ARTICULO ADD CONSTRAINT PK_ARTICULO PRIMARY KEY (NUM_ARTICULO);
CREATE SEQUENCE SEC_NUMARTICULO START WITH 1 INCREMENT BY 1 MAXVALUE 99999999999 MINVALUE 1;

ALTER TABLE INCLUYE ADD CONSTRAINT PK_INCLUYE PRIMARY KEY (NUM_PEDIDO, NUM_ARTICULO);
ALTER TABLE INCLUYE ADD CONSTRAINT FK_INCLUYE FOREIGN KEY (NUM_PEDIDO) REFERENCES PEDIDO (NUM_PEDIDO);
ALTER TABLE INCLUYE ADD CONSTRAINT FK2_INCLUYE FOREIGN KEY (NUM_ARTICULO) REFERENCES ARTICULO (NUM_ARTICULO);

ALTER TABLE FABRICA ADD CONSTRAINT PK_FABRICA PRIMARY KEY (NUM_FABRICA);
CREATE SEQUENCE SEC_NUMFABRICA START WITH 1 INCREMENT BY 1 MAXVALUE 99999999999 MINVALUE 1;

ALTER TABLE DISTRIBUYE ADD CONSTRAINT PK_DISTRIBUYE PRIMARY KEY (NUM_ARTICULO, NUM_FABRICA);
ALTER TABLE DISTRIBUYE ADD CONSTRAINT FK_DISTRIBUYE FOREIGN KEY (NUM_ARTICULO) REFERENCES ARTICULO (NUM_ARTICULO);
ALTER TABLE DISTRIBUYE ADD CONSTRAINT FK2_DISTRIBUYE FOREIGN KEY (NUM_FABRICA) REFERENCES FABRICA (NUM_FABRICA);

INSERT INTO CLIENTE VALUES (SEC_NUMCLIENTE.NEXTVAL, 1000, 500, 10);
INSERT INTO ARTICULO VALUES (SEC_NUMARTICULO.NEXTVAL, 'Teclado mecánico');
INSERT INTO FABRICA VALUES (SEC_NUMFABRICA.NEXTVAL, 954123456);

SELECT * FROM CLIENTE;
SELECT * FROM ARTICULO;
SELECT * FROM FABRICA;