CREATE TABLE EMPLEADO(
    COD_EMP NUMBER (10),
    NIF VARCHAR2 (9),
    NOMBRE VARCHAR2 (15),
    APELLIDOS VARCHAR2 (15),
    DIRECCION VARCHAR2 (100),
    TELEFONO NUMBER (9),
    FECHA_NAC DATE,
    SALARIO NUMBER (7,2)
);

CREATE TABLE CURSO(
    COD_CURSO NUMBER (10),
    NOMBRE VARCHAR2 (15),
    DURACION NUMBER (10),
    COSTE NUMBER (10,2)
);

CREATE TABLE EMP_CAPACITADO(
    COD_EMP NUMBER (10)
);

CREATE TABLE EDICION(
    COD_CURSO NUMBER (10),
    FECHA_INICIO DATE,
    LUGAR VARCHAR2 (10),
    HORARIO VARCHAR2 (10),
    PROFESOR VARCHAR2 (15)
);

CREATE TABLE RECIBE(
    COD_EMPLEADO NUMBER (10),
    COD_CURSO NUMBER (10),
    FECHA_INICIO DATE
);

CREATE TABLE PRERREQUISITO(
    CURSO_SOLICITADO NUMBER (10),
    CURSO_PREVIO NUMBER (10),
    OBLIGATORIO VARCHAR2 (2)
);

CREATE TABLE EMP_NO_CAPACITADO(
    COD_EMP NUMBER (10)
);


ALTER TABLE EMPLEADO ADD CONSTRAINT PK_EMPLEADO PRIMARY KEY (COD_EMP);
ALTER TABLE EMPLEADO ADD CONSTRAINT UQ_EMPLEADO UNIQUE (NIF);

ALTER TABLE CURSO ADD CONSTRAINT PK_CURSO PRIMARY KEY (COD_CURSO);

ALTER TABLE EMP_CAPACITADO ADD CONSTRAINT PK_EMP_CAPACITADO PRIMARY KEY (COD_EMP);
ALTER TABLE EMP_CAPACITADO ADD CONSTRAINT FK_EMP_CAPACITADO FOREIGN KEY (COD_EMP) REFERENCES EMPLEADO (COD_EMP);

ALTER TABLE EDICION ADD CONSTRAINT PK_EDICION PRIMARY KEY (COD_CURSO, FECHA_INICIO);
ALTER TABLE EDICION ADD CONSTRAINT FK_EDICION FOREIGN KEY (COD_CURSO) REFERENCES CURSO (COD_CURSO);

ALTER TABLE RECIBE ADD CONSTRAINT PK_RECIBE PRIMARY KEY (COD_EMPLEADO, COD_CURSO, FECHA_INICIO);
ALTER TABLE RECIBE ADD CONSTRAINT FK_RECIBE FOREIGN KEY (COD_EMPLEADO) REFERENCES EMPLEADO (COD_EMP);
ALTER TABLE RECIBE ADD CONSTRAINT FK2_RECIBE FOREIGN KEY (COD_CURSO, FECHA_INICIO) REFERENCES EDICION (COD_CURSO, FECHA_INICIO);

ALTER TABLE PRERREQUISITO ADD CONSTRAINT PK_PRERREQUISITO PRIMARY KEY (CURSO_SOLICITADO, CURSO_PREVIO);
ALTER TABLE PRERREQUISITO ADD CONSTRAINT FK_PRERREQUISITO FOREIGN KEY (CURSO_SOLICITADO) REFERENCES CURSO (COD_CURSO);
ALTER TABLE PRERREQUISITO ADD CONSTRAINT FK2_PRERREQUISITO FOREIGN KEY (CURSO_PREVIO) REFERENCES CURSO (COD_CURSO);
ALTER TABLE PRERREQUISITO ADD CONSTRAINT CHK_OBLIGATORIO CHECK (OBLIGATORIO IN ('S','N'));

ALTER TABLE EMP_NO_CAPACITADO ADD CONSTRAINT PK_EMP_NO_CAPACITADO PRIMARY KEY (COD_EMP);
ALTER TABLE EMP_NO_CAPACITADO ADD CONSTRAINT FK_EMP_NO_CAPACITADO FOREIGN KEY (COD_EMP) REFERENCES EMPLEADO (COD_EMP);

