--alter session set "_oracle_script"=true;  
--create user joelruiz identified by joelruiz;
--GRANT CONNECT, RESOURCE, DBA TO joelruiz;

DROP TABLE ENFERMO CASCADE CONSTRAINTS;
DROP TABLE MEDICO CASCADE CONSTRAINTS;
DROP TABLE HABITACION CASCADE CONSTRAINTS;
DROP TABLE INGRESO CASCADE CONSTRAINTS;
DROP TABLE VISITA CASCADE CONSTRAINTS;

CREATE TABLE ENFERMO (
    COD_INSCRIPCION NUMBER(10),
    NSS VARCHAR2 (10),
    NOMBRE VARCHAR2 (15),
    SEXO VARCHAR2 (1),
    CONSTRAINT PK_ENFERMO PRIMARY KEY (COD_INSCRIPCION)
);

CREATE TABLE MEDICO (
    COD_MEDICO NUMBER(10),
    NOMBRE VARCHAR2 (15),
    ESPECIALIDAD VARCHAR2 (15) DEFAULT 'FAM',
    COD_DIRECTOR NUMBER(10),
    CONSTRAINT PK_MEDICO PRIMARY KEY (COD_MEDICO),
    CONSTRAINT FK_MEDICO FOREIGN KEY (COD_DIRECTOR) REFERENCES MEDICO (COD_MEDICO) ON DELETE SET NULL
); 

CREATE TABLE HABITACION (
    NUM_HAB NUMBER(10),
    NUMERO_CAMAS NUMBER(10),
    CONSTRAINT PK_HABITACION PRIMARY KEY (NUM_HAB),
    CONSTRAINT CHK_NUM_HAB CHECK (NUM_HAB >= 100 AND NUM_HAB <= 200),
    CONSTRAINT CHK_NUMERO_CAMAS CHECK (NUMERO_CAMAS <= 4)
);

CREATE TABLE INGRESO (
    COD_INGRESO NUMBER(10),
    COD_INSCRIPCION NUMBER(10),
    FECHA_INGRESO DATE DEFAULT SYSDATE,
    FECHA_ALTA DATE,
    NUM_HAB NUMBER(10),
    CONSTRAINT PK_INGRESO PRIMARY KEY (COD_INGRESO),
    CONSTRAINT FK_INGRESO FOREIGN KEY (NUM_HAB) REFERENCES HABITACION (NUM_HAB),
    CONSTRAINT FK2_INGRESO FOREIGN KEY (COD_INSCRIPCION) REFERENCES ENFERMO (COD_INSCRIPCION) ON DELETE CASCADE,
	CONSTRAINT CHK_FECHA_ALTA CHECK (FECHA_ALTA IS NULL OR FECHA_ALTA > FECHA_INGRESO)
);  

CREATE TABLE VISITA (
    COD_MEDICO NUMBER(10),
    COD_INSCRIPCION NUMBER(10),
    FECHA DATE,
    DIAGNOSTICO VARCHAR2 (15),
    CONSTRAINT PK_VISITA PRIMARY KEY (COD_MEDICO, COD_INSCRIPCION),
    CONSTRAINT FK_VISITA FOREIGN KEY (COD_MEDICO) REFERENCES MEDICO (COD_MEDICO) ON DELETE CASCADE ,
    CONSTRAINT FK2_VISITA FOREIGN KEY (COD_INSCRIPCION) REFERENCES ENFERMO (COD_INSCRIPCION) ON DELETE CASCADE
);
