CREATE TABLE CABALLOS
(
	CODCABALLO VARCHAR2(4),
	NOMBRE VARCHAR2(20) NOT NULL,
	PESO NUMBER(3),
	FECHA_NACIMIENTO DATE,
	PROPIETARIO VARCHAR2(25),
	NACIONALIDAD VARCHAR2(20),
	CONSTRAINT PK_CABALLOS PRIMARY KEY (CODCABALLO)
);

CREATE TABLE CARRERAS
(
	CODCARRERA VARCHAR2(4),
	FECHA_HORA DATE,
	IMPORTE_PREMIO NUMBER(6),
	APUESTA_LIMITE NUMBER(10,2),
	CONSTRAINT PK_CARRERAS PRIMARY KEY (CODCARRERA)
);

CREATE TABLE PARTICIPACIONES
(
	CODCABALLO VARCHAR2(4),
	CODCARRERA VARCHAR2(4),
	DORSAL NUMBER(2) NOT NULL,
	JOCKEY VARCHAR2(10) NOT NULL,
	POSICION_FINAL NUMBER(2),
	CONSTRAINT PK_PARTICIPACIONES PRIMARY KEY (CODCABALLO, CODCARRERA),
	CONSTRAINT FK1_PARTICIPACIONES FOREIGN KEY (CODCABALLO) REFERENCES CABALLOS (CODCABALLO) ON DELETE CASCADE,
	CONSTRAINT FK2_PARTICIPACIONES FOREIGN KEY (CODCARRERA) REFERENCES CARRERAS (CODCARRERA) ON DELETE CASCADE
);

CREATE TABLE CLIENTES
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(20),
	NACIONALIDAD VARCHAR2(20),
	CONSTRAINT PK_CLIENTE PRIMARY KEY(DNI)
);

CREATE TABLE APUESTAS
(
	DNICLIENTE VARCHAR2(10),
	CODCABALLO VARCHAR2(4),
	CODCARRERA VARCHAR2(4),
	IMPORTE NUMBER(6) DEFAULT 300 NOT NULL,
	TANTOPORUNO NUMBER(4,2),
	CONSTRAINT PK_APUESTAS PRIMARY KEY (DNICLIENTE, CODCABALLO, CODCARRERA),
	CONSTRAINT FK1_APUESTAS FOREIGN KEY (DNICLIENTE) REFERENCES CLIENTES (DNI) ON DELETE CASCADE,
	CONSTRAINT FK2_APUESTAS FOREIGN KEY (CODCABALLO) REFERENCES CABALLOS (CODCABALLO) ON DELETE CASCADE,
	CONSTRAINT FK3_APUESTAS FOREIGN KEY (CODCARRERA) REFERENCES CARRERAS (CODCARRERA) ON DELETE CASCADE
);

ALTER TABLE CABALLOS ADD CONSTRAINT CHK1_CABALLOS CHECK (PESO BETWEEN 240 AND 300);
ALTER TABLE CABALLOS ADD CONSTRAINT CHK2_CABALLOS CHECK (FECHA_NACIMIENTO > DATE '2000-01-01');
-- EXTRACT (YEAR FROM FECHA_NACIMIENTO)
ALTER TABLE CABALLOS ADD CONSTRAINT CHK3_CABALLOS CHECK (NACIONALIDAD = UPPER(NACIONALIDAD));

ALTER TABLE CARRERAS ADD CONSTRAINT CHK1_CARRERAS CHECK (TO_CHAR(FECHA_HORA, 'HH24:MI')BETWEEN '09:00' AND '14:30');
ALTER TABLE CARRERAS ADD CONSTRAINT CHK2_CARRERAS CHECK (APUESTA_LIMITE < 20000);

ALTER TABLE PARTICIPACIONES ADD CONSTRAINT CHK_PARTICIPACIONES CHECK (POSICION_FINAL > 0);

ALTER TABLE CLIENTES ADD CONSTRAINT CHK1_CLIENTES CHECK (REGEXP_LIKE(DNI,'^[0-9]{8}[A-Z]$')); 
ALTER TABLE CLIENTES ADD CONSTRAINT CHK2_CLIENTES CHECK (NACIONALIDAD = UPPER(NACIONALIDAD));

ALTER TABLE APUESTAS ADD CONSTRAINT CHK_APUESTAS CHECK (TANTOPORUNO > 1);

-- 2. Inserta el registro o registros necesarios para guardar la siguiente información:
-- El cliente escocés realiza una apuesta al caballo más pesado de la primera carrera que se corra en el verano de 2009 por un importe de 2000 euros. En ese momento ese caballo en esa carrera se paga 30 a 1.
-- Si es necesario algún dato invéntatelo, pero sólo los datos que sean estrictamente necesaria.

INSERT INTO CARRERAS VALUES ('C1', TO_DATE('2009-06-15 10:00', 'YYYY-MM-DD HH24:MI'), 5000, 15000);
INSERT INTO CARRERAS VALUES ('C6', TO_DATE('2010-06-15 12:00',' YYYY-MM-DD HH24:MI'), 6000, 18000);

INSERT INTO CABALLOS VALUES ('H1', 'RAYO', 280, TO_DATE('10-05-2005','DD-MM-YYYY'), 'Michael', 'BRITÁNICA');
INSERT INTO CABALLOS VALUES ('H2', 'TRUENO', 300, TO_DATE('20-03-2004','DD-MM-YYYY'), 'Luis', 'ESPAÑOLA');

INSERT INTO CLIENTES VALUES ('12345678A', 'Scott', 'ESCOCESA');


INSERT INTO PARTICIPACIONES VALUES ('H2', 'C1', 1, 'J.Smith', 1);

-- 3. Inscribe a 2 caballos  en la carrera cuyo código es C6. La carrera aún no se ha celebrado. Invéntate los jockeys y los dorsales y los caballos.
INSERT INTO CABALLOS VALUES ('H3', 'RELÁMPAGO', 275, TO_DATE('20-05-2007','DD-MM-YYYY'), 'Joseph', 'ÁRABE');
INSERT INTO CABALLOS VALUES ('H4', 'PERICO', 285, TO_DATE('24-08-2006','DD-MM-YYYY'), 'Joan', 'ESPAÑOLA')


INSERT INTO PARTICIPACIONES VALUES ('H3', 'C6', 2, 'J.Donovan', 2);
INSERT INTO PARTICIPACIONES VALUES ('H4', 'C6', 1, 'O.Gonzalez',1);

-- SELECT * FROM PARTICIPACIONES;

-- 4. Inserta dos carreras con los datos que creas necesario.
INSERT INTO CARRERAS VALUES ('C2', TO_DATE('2009-08-15 10:30', 'YYYY-MM-DD HH24:MI'), 7000, 15000);
INSERT INTO CARRERAS VALUES ('C3', TO_DATE('2010-08-15 11:00',' YYYY-MM-DD HH24:MI'), 9000, 18000);


-- 5. Quita el campo propietario de la tabla caballos
ALTER TABLE CABALLOS DROP COLUMN PROPIETARIO;

-- 6. Añadir las siguientes restricciones a las tablas:
    --• En la Tabla Participaciones los nombres de los jockeys tienen siempre las iniciales en mayúsculas.
    --• La temporada de carreras transcurre del 10 de Marzo al 10 de Noviembre.
    --• La nacionalidad de los caballos sólo puede ser Española, Británica o Árabe.
    --Si los datos que has introducidos no cumplen las restricciones haz los cambios necesarios para ellos.

ALTER TABLE PARTICIPACIONES
ADD CONSTRAINT CHK_JOCKEY
CHECK (JOCKEY=INITCAP(JOCKEY));

ALTER TABLE CARRERAS
ADD CONSTRAINT CHK_TEMPORADA
CHECK (EXTRACT(MONTH FROM FECHA_HORA = 3 AND DAY FROM FECHA_HORA > 10) OR (MONTH BETWEEN 4 AND 10) OR (MES=11 AND DAY < 10)
);

ALTER TABLE CABALLOS
ADD CONSTRAINT CHK_NACIONALIDAD
CHECK (NACIONALIDAD IN ('ESPAÑOLA','BRITÁNICA','ÁRABE'));


-- 7. Borra las carreras en las que no hay caballos inscritos.
DELETE FROM caballo WHERE codcaballo NOT IN (SELECT codcaballo FROM participaciones);

--8. Añade un campo llamado código en el campo clientes, que no permita valores nulos ni repetidos
ALTER TABLE CLIENTES ADD CODIGO VARCHAR2(10) NOT NULL UNIQUE;

-- 9. Nos hemos equivocado y el código C6 de la carrera en realidad es C66.
INSERT INTO CARRERAS VALUES ('C66', TO_DATE('2010-06-15 12:00',' YYYY-MM-DD HH24:MI'), 6000, 18000);
UPDATE PARTICIPACIONES
SET CODCARRERA = 'C66'
WHERE CODCARRERA = 'C6';
DELETE * FROM CARRERAS WHERE CODCARRERA = 'C6';

-- 10. Añade un campo llamado premio a la tabla apuestas.
ALTER TABLE APUESTAS ADD PREMIO NUMBER(8,2);

-- 11. Borra todas las tablas y datos con el número menor de instrucciones posibles.
DROP TABLE APUESTAS CASCADE CONSTRAINT;
DROP TABLE CLIENTES CASCADE CONSTRAINT;
DROP TABLE PARTICIPACIONES CASCADE CONSTRAINT;
DROP TABLE CARRERAS CASCADE CONSTRAINT;
DROP TABLE CABALLOS CASCADE CONSTRAINT;
