CREATE TABLE PROFESORES(
    NOMBRE VARCHAR2(30),
    APELLIDO1 VARCHAR2(30),
    APELLIDO2 VARCHAR2(30),
    DNI NUMBER(10),
    DIRECCION VARCHAR2(50),
    TITULO VARCHAR2(40),
    GANA NUMBER(8,2),
    CONSTRAINT PK_PROFESORES PRIMARY KEY(DNI)
);

CREATE TABLE CURSOS(
    NOMBRE_CURSO VARCHAR2(40),
    COD_CURSO NUMBER(5),
    DNI_PROFESOR NUMBER(10),
    MAXIMO_ALUMNOS NUMBER(3),
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    NUM_HORAS NUMBER(4),
    CONSTRAINT PK_CURSOS PRIMARY KEY(COD_CURSO),
    CONSTRAINT FK_CURSOS_PROF FOREIGN KEY(DNI_PROFESOR) REFERENCES PROFESORES(DNI)
);

CREATE TABLE ALUMNOS(
    NOMBRE VARCHAR2(30),
    APELLIDO1 VARCHAR2(30),
    APELLIDO2 VARCHAR2(30),
    DNI NUMBER(10),
    DIRECCION VARCHAR2(50),
    SEXO VARCHAR2(1),
    FECHA_NACIMIENTO DATE,
    CURSO NUMBER(5),
    CONSTRAINT PK_ALUMNOS PRIMARY KEY(DNI),
    CONSTRAINT FK_ALUMNOS_CURSO FOREIGN KEY(CURSO) REFERENCES CURSOS(COD_CURSO),
    CONSTRAINT CHK_ALUMNOS_SEXO CHECK(SEXO IN('H','M'))
);


INSERT INTO PROFESORES VALUES('Juan','Arch','López',32432455,'Puerta Negra, 4','Ing. Informática',7500);
INSERT INTO PROFESORES VALUES('María','Oliva','Rubio',43215643,'Juan Alfonso 32','Lda. Fil. Inglesa',5400);

INSERT INTO CURSOS VALUES('Inglés Básico',1,43215643,15,TO_DATE('01/11/00','DD/MM/YY'),TO_DATE('22/12/00','DD/MM/YY'),120);
INSERT INTO CURSOS VALUES('Administración Linux',2,32432455,NULL,TO_DATE('01/09/00','DD/MM/YY'),NULL,80);

INSERT INTO ALUMNOS VALUES('Lucas','Manilva','López',123523,'Alhamar, 3','H',TO_DATE('01/11/79','DD/MM/YY'),1);
INSERT INTO ALUMNOS VALUES('Antonia','López','Alcantara',2567567,'Maniquí, 21','M',NULL,2);
INSERT INTO ALUMNOS VALUES('Manuel','Alcantara','Pedrós',3123689,'Julian, 2','H',NULL,1);


-- ERROR: curso 3 no existe
INSERT INTO ALUMNOS VALUES('José','Pérez','Caballar',4896765,'Jarcha,5','H',TO_DATE('03/02/77','DD/MM/YY'),3);

-- 3. INSERT ERRÓNEO (SEXO = P)
INSERT INTO ALUMNOS VALUES('Sergio','Navas','Retal',123523,NULL,'P',NULL,1);

-- 4. INSERT ERRÓNEO (PK DUPLICADA)
INSERT INTO PROFESORES VALUES('Juan','Arch','López',32432455,'Puerta Negra, 4','Ing. Informática',NULL);

-- 5. INSERT ALUMNA SIN CURSO
INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO,FECHA_NACIMIENTO)
VALUES('María','Jaén','Sevilla',789678,'Martos, 5','M',NULL);

-- 6. CORREGIR FECHA DE ANTONIA
UPDATE ALUMNOS SET FECHA_NACIMIENTO=TO_DATE('23/12/1976','DD/MM/YYYY')
WHERE NOMBRE LIKE 'Antonia' AND APELLIDO1='López';

-- 7. CAMBIAR CURSO A 5 (ERROR: NO EXISTE)
UPDATE ALUMNOS SET CURSO=5
WHERE NOMBRE LIKE 'Antonia' AND APELLIDO1='López';

-- 8. ELIMINAR PROFESORA INEXISTENTE
DELETE FROM PROFESORES WHERE NOMBRE LIKE 'Laura' AND APELLIDO1='Jiménez';

-- 9. BORRAR CURSO 1 (ERROR: TIENE ALUMNOS)
DELETE FROM CURSOS WHERE COD_CURSO=1;

-- 10. AÑADIR CAMPO
ALTER TABLE CURSOS ADD NUMERO_ALUMNOS NUMBER(3);

-- 11. FECHA POR DEFECTO A NULOS
UPDATE ALUMNOS SET FECHA_NACIMIENTO=TO_DATE('01/01/2012','DD/MM/YYYY')
WHERE FECHA_NACIMIENTO IS NULL;

-- 12. BORRAR CAMPO SEXO
ALTER TABLE ALUMNOS DROP COLUMN SEXO;

-- 13. SUBIR 20% A INFORMÁTICA
UPDATE PROFESORES SET GANA=GANA*1.20
WHERE UPPER(TITULO) LIKE '%Informática%';

-- 14. CAMBIAR DNI DE JUAN ARCH
UPDATE PROFESORES SET DNI=1234567
WHERE NOMBRE='Juan' AND APELLIDO1='Arch';

-- 15. CAMBIAR DNI A TODOS LOS INFORMÁTICOS (ERROR SI HAY MÁS DE UNO)
UPDATE PROFESORES SET DNI=7654321
WHERE TITULO LIKE '%Informática%';

-- 16. CAMBIAR SEXO DE MARÍA JAÉN (ERROR: COLUMNA YA BORRADA)
UPDATE ALUMNOS SET SEXO='F'
WHERE NOMBRE='María' AND APELLIDO1='Jaén';


-- ADICIONALES MOODLE
CREATE TABLE DEPARTAMENTOS(
    CODIGO NUMBER(10),
    DESCRIPCION VARCHAR2(100),
    CONSTRAINT PK_DEPARTAMENTOS PRIMARY KEY(CODIGO)
);

CREATE SEQUENCE SEQ_DEPARTAMENTOS START WITH 1 INCREMENT BY 1;

INSERT INTO DEPARTAMENTOS VALUES(SEQ_DEPARTAMENTOS.NEXTVAL,'Contabilidad');
INSERT INTO DEPARTAMENTOS VALUES(SEQ_DEPARTAMENTOS.NEXTVAL,'Marketing');
INSERT INTO DEPARTAMENTOS VALUES(SEQ_DEPARTAMENTOS.NEXTVAL,'Recursos Humanos');
INSERT INTO DEPARTAMENTOS VALUES(SEQ_DEPARTAMENTOS.NEXTVAL,'Informática');

