CREATE TABLE CABALLOS(
    COD_CABALLO VARCHAR2(4),
    NOMBRE VARCHAR2(20) NOT NULL,
    PESO NUMBER(3) Entre 240 y 300,
    FECHA_NACIMIENTO DATE > 2000,
    PROPIETARIO VARCHAR2(25),
    NACIONALIDAD VARCHAR2(20) Todos los caracteres en mayúsculas,
    CONSTRAINT PK_CABALLOS PRIMARY KEY (COD_CABALLO)
);

CREATE TABLE PARTICIPACIONES(
    COD_CABALLO VARCHAR2(4),
    COD_CARRERA VARCHAR2(4),
    DORSAL NUMBER(2) NOT NULL,
    JOCKEY VARCHAR2(10) NOT NULL,
    POSICION_FINAL NUMBER(2) Numero positivo,
    CONSTRAINT PK_PARTICIPACIONES PRIMARY KEY (COD_CABALLO, COD_CARRERA),
    CONSTRAINT FK_PARTICIPACIONES FOREIGN KEY (COD_CABALLO) REFERENCES CABALLOS(COD_CABALLO)) con borrado restringido,
    CONSTRAINT FK2_PARTICIPACIONES FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA) con borrado restringido
);

CREATE TABLE CARRERAS(
    COD_CARRERA VARCHAR2(4),
    FECHA_Y_HORA DATE, HORA ENTRE LAS 9 Y LAS 14:30
    IMPORTE_PREMIO NUMBER(6),
    APUESTA_LIMITE NUMBER(7,2), MÁS 2 DECIMALES < 20000
    CONSTRAINT PK_CARRERAS PRIMARY KEY (COD_CARRERA)
);

CREATE TABLE APUESTAS(
    DNI_CLIENTE VARCHAR2(10),
    COD_CABALLO VARCHAR2(4),
    COD_CARRERA VARCHAR2(4),
    IMPORTE NUMBER(6) NOT NULL, POR DEFECTO 300
    TANTO_POR_UNO NUMBER(6,2), DECIMALES MAYOR QUE 1
    CONSTRAINT PK_APUESTAS PRIMARY KEY (DNI_CLIENTE, COD_CABALLO, COD_CARRERA),
    CONSTRAINT FK_APUESTAS FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES(DNI), ON DELETE CASCADE
    CONSTRAINT FK_APUESTAS FOREIGN KEY (COD_CABALLO) REFERENCES CABALLOS(COD_CABALLO), ON DELETE CASCADE
    CONSTRAINT FK_APUESTAS FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA), ON DELETE CASCADE
);

CREATE TABLE CLIENTES(
    DNI VARCHAR2(10), FORMATO 8 NÚMEROS Y UNA LETRA EN MAYÚSCULAS
    NOMBRE VARCHAR2(20),
    NACIONALIDAD VARCHAR2(20), TODOS LOS DATOS DEBEN ESTAR EN MAYÚSCULAS
    CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI)
);
