
DROP TABLE DEPARTAMENTO CASCADE CONSTRAINTS;

DROP TABLE EMPLEADO CASCADE CONSTRAINTS;

DROP SEQUENCE SQ_DEPARTAMENTO;

DROP TABLE DEPARTAMENTO_BACKUP CASCADE CONSTRAINTS;


CREATE TABLE DEPARTAMENTO(
    CODIGO NUMBER(10),
    NOMBRE VARCHAR2(100),
    PRESUPUESTO NUMBER(10,2),
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (CODIGO)
);

CREATE TABLE EMPLEADO(
    CODIGO NUMBER(10),
    NIF VARCHAR2(9),
    NOMBRE VARCHAR2(100),
    APELLIDO1 VARCHAR2(100),
    APELLIDO2 VARCHAR2(100),
    CODIGO_DEPARTAMENTO NUMBER(10),
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_EMPLEADO FOREIGN KEY (CODIGO_DEPARTAMENTO) REFERENCES DEPARTAMENTO(CODIGO)
);

-- Primero EJ3: añadir GASTOS antes de insertar datos
ALTER TABLE DEPARTAMENTO ADD GASTOS NUMBER(12,2);

-- DATOS INICIALES
INSERT INTO DEPARTAMENTO VALUES (1, 'Desarrollo', 120000, 6000);
INSERT INTO DEPARTAMENTO VALUES (2, 'Sistemas', 150000, 21000);
INSERT INTO DEPARTAMENTO VALUES (3, 'Recursos Humanos', 280000, 25000);
INSERT INTO DEPARTAMENTO VALUES (4, 'Contabilidad', 110000, 3000);
INSERT INTO DEPARTAMENTO VALUES (5, 'I+D', 375000, 380000);
INSERT INTO DEPARTAMENTO VALUES (6, 'Proyectos', 0, 0);
INSERT INTO DEPARTAMENTO VALUES (7, 'Publicidad', 0, 1000);

INSERT INTO EMPLEADO VALUES (1, '32481596F', 'Aarón', 'Rivero', 'Gómez', 1);
INSERT INTO EMPLEADO VALUES (2, 'Y5575632D', 'Adela', 'Salas', 'Díaz', 2);
INSERT INTO EMPLEADO VALUES (3, 'R6970642B', 'Adolfo', 'Rubio', 'Flores', 3);
INSERT INTO EMPLEADO VALUES (4, '77705545E', 'Adrián', 'Suárez', NULL, 4);
INSERT INTO EMPLEADO VALUES (5, '17087203C', 'Marcos', 'Loyola', 'Méndez', 5);
INSERT INTO EMPLEADO VALUES (6, '38382980M', 'María', 'Santana', 'Moreno', 1);
INSERT INTO EMPLEADO VALUES (7, '80576669X', 'Pilar', 'Ruiz', NULL, 2);
INSERT INTO EMPLEADO VALUES (8, '71651431Z', 'Pepe', 'Ruiz', 'Santana', 3);
INSERT INTO EMPLEADO VALUES (9, '56399183D', 'Juan', 'Gómez', 'López', 2);
INSERT INTO EMPLEADO VALUES (10, '46384486H', 'Diego','Flores', 'Salas', 5);
INSERT INTO EMPLEADO VALUES (11, '67389283A', 'Marta','Herrera', 'Gil', 1);
INSERT INTO EMPLEADO VALUES (12, '41234836R', 'Irene','Salas', 'Flores', NULL);
INSERT INTO EMPLEADO VALUES (13, '82635162B', 'Juan Antonio','Sáez', 'Guerrero', NULL);

-- EJ1
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE, PRESUPUESTO) VALUES (8, 'Calidad', 50000);

-- EJ2
CREATE SEQUENCE SQ_DEPARTAMENTO START WITH 14 INCREMENT BY 1;
INSERT INTO DEPARTAMENTO (CODIGO, NOMBRE, PRESUPUESTO) VALUES (SQ_DEPARTAMENTO.NEXTVAL, 'Logística', 30000);

-- EJ3 (columnas gastos la he agregado arriba)
INSERT INTO DEPARTAMENTO VALUES (9, 'Soporte', 40000, 5000);

-- EJ4
INSERT INTO EMPLEADO VALUES (14, '12345678A', 'Lucía', 'Pérez', 'Romero', 8);

-- EJ5
--INSERT INTO EMPLEADO (NIF, NOMBRE, APELLIDO1, APELLIDO2, CODIGO_DEPARTAMENTO) VALUES ('87654321B', 'Carlos', 'López', 'Santos', 9);

-- EJ6
CREATE TABLE DEPARTAMENTO_BACKUP AS
SELECT * FROM DEPARTAMENTO;

-- EJ7
DELETE FROM DEPARTAMENTO
WHERE NOMBRE = 'Proyectos';

-- EJ8
UPDATE EMPLEADO
SET CODIGO_DEPARTAMENTO = NULL
WHERE CODIGO_DEPARTAMENTO = 1;

DELETE FROM DEPARTAMENTO
WHERE NOMBRE = 'Desarrollo';

-- EJ9
UPDATE EMPLEADO e 
SET CODIGO_DEPARTAMENTO = NULL
WHERE CODIGO_DEPARTAMENTO = 3;

UPDATE DEPARTAMENTO
SET CODIGO = 30
WHERE CODIGO = 3;

UPDATE EMPLEADO e  
SET CODIGO_DEPARTAMENTO = 30
WHERE CODIGO_DEPARTAMENTO IS NULL;

-- EJ10
UPDATE DEPARTAMENTO
SET CODIGO = 40
WHERE NOMBRE = 'Publicidad';

-- EJ11
UPDATE DEPARTAMENTO
SET PRESUPUESTO = PRESUPUESTO + 50000
WHERE PRESUPUESTO < 20000;

-- EJ12
DELETE FROM EMPLEADO
WHERE CODIGO_DEPARTAMENTO IS NULL;

