DROP TABLE IF EXISTS CLIENTE;

DROP TABLE IF EXISTS DETALLE_PEDIDO;

DROP TABLE IF EXISTS EMPLEADO;

DROP TABLE IF EXISTS GAMA_PRODUCTO;

DROP TABLE IF EXISTS OFICINA;

DROP TABLE IF EXISTS PAGO;

DROP TABLE IF EXISTS PEDIDO;

DROP TABLE IF EXISTS PRODUCTO;


CREATE TABLE GAMA_PRODUCTO (
    GAMA VARCHAR(50),
    DESCRIPCION_TEXTO VARCHAR(3000),
    DESCRIPCION_HTML VARCHAR(3000),
    IMAGEN VARCHAR(256),
    CONSTRAINT PK_GAMA_PRODUCTO PRIMARY KEY (GAMA)
);

CREATE TABLE PRODUCTO (
    CODIGO_PRODUCTO VARCHAR(15),
    NOMBRE VARCHAR(70),
    GAMA VARCHAR(50),
    DIMENSIONES VARCHAR(25),
    PROVEEDOR VARCHAR(50),
    DESCRIPCION VARCHAR(3000),
    CANTIDAD_EN_STOCK INT,
    PRECIO_VENTA DECIMAL(15,2),
    PRECIO_PROVEEDOR DECIMAL(15,2),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO_PRODUCTO),
    CONSTRAINT FK_PRODUCTO_GAMA FOREIGN KEY (GAMA) REFERENCES GAMA_PRODUCTO(GAMA)
);

CREATE TABLE OFICINA (
    CODIGO_OFICINA VARCHAR(10),
    CIUDAD VARCHAR(30),
    PAIS VARCHAR(50),
    REGION VARCHAR(50),
    CODIGO_POSTAL VARCHAR(10),
    TELEFONO VARCHAR(20),
    LINEA_DIRECCION1 VARCHAR(50),
    LINEA_DIRECCION2 VARCHAR(50),
    CONSTRAINT PK_OFICINA PRIMARY KEY (CODIGO_OFICINA)
);

CREATE TABLE EMPLEADO (
    CODIGO_EMPLEADO INT,
    NOMBRE VARCHAR(50),
    APELLIDO1 VARCHAR(50),
    APELLIDO2 VARCHAR(50),
    EXTENSION VARCHAR(10),
    EMAIL VARCHAR(100),
    CODIGO_OFICINA VARCHAR(10),
    CODIGO_JEFE INT,
    PUESTO VARCHAR(50),
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (CODIGO_EMPLEADO),
    CONSTRAINT FK_EMPLEADO_OFICINA FOREIGN KEY (CODIGO_OFICINA) REFERENCES OFICINA(CODIGO_OFICINA),
    CONSTRAINT FK_EMPLEADO_JEFE FOREIGN KEY (CODIGO_JEFE) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE CLIENTE (
    CODIGO_CLIENTE INT,
    NOMBRE_CLIENTE VARCHAR(50),
    NOMBRE_CONTACTO VARCHAR(30),
    APELLIDO_CONTACTO VARCHAR(30),
    TELEFONO VARCHAR(15),
    FAX VARCHAR(15),
    LINEA_DIRECCION1 VARCHAR(50),
    LINEA_DIRECCION2 VARCHAR(50),
    CIUDAD VARCHAR(50),
    REGION VARCHAR(50),
    PAIS VARCHAR(50),
    CODIGO_POSTAL VARCHAR(10),
    CODIGO_EMPLEADO_REP_VENTAS INT,
    LIMITE_CREDITO DECIMAL(15,2),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (CODIGO_CLIENTE),
    CONSTRAINT FK_CLIENTE_REP FOREIGN KEY (CODIGO_EMPLEADO_REP_VENTAS) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE PEDIDO (
    CODIGO_PEDIDO INT,
    FECHA_PEDIDO DATE,
    FECHA_ESPERADA DATE,
    FECHA_ENTREGA DATE,
    ESTADO VARCHAR(15),
    COMENTARIOS VARCHAR(3000),
    CODIGO_CLIENTE INT,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (CODIGO_PEDIDO),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
);

CREATE TABLE DETALLE_PEDIDO (
    CODIGO_PEDIDO INT,
    CODIGO_PRODUCTO VARCHAR(15),
    CANTIDAD INT,
    PRECIO_UNIDAD DECIMAL(15,2),
    NUMERO_LINEA INT,
    CONSTRAINT PK_DETALLE_PEDIDO PRIMARY KEY (CODIGO_PEDIDO, CODIGO_PRODUCTO),
    CONSTRAINT FK_DETALLE_PEDIDO_PEDIDO FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO(CODIGO_PEDIDO),
    CONSTRAINT FK_DETALLE_PEDIDO_PRODUCTO FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO)
);

CREATE TABLE PAGO (
    CODIGO_CLIENTE INT,
    FORMA_PAGO VARCHAR(40),
    ID_TRANSACCION VARCHAR(50),
    FECHA_PAGO DATE,
    TOTAL INT,
    CONSTRAINT PK_PAGO PRIMARY KEY (CODIGO_CLIENTE, ID_TRANSACCION),
    CONSTRAINT FK_PAGO_CLIENTE FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
);
