CREATE TABLE PROFESORES
(
	NOMBRE VARCHAR2(30),
	APELLIDO1 VARCHAR2(30),
	APELLIDO2 VARCHAR2(30),
	DNI VARCHAR2(9),
	DIRECCION VARCHAR2(40),
	TITULO VARCHAR2(40),
	GANA NUMBER(6),
	CONSTRAINT PK_PROFESORES PRIMARY KEY(DNI)
);

CREATE TABLE CURSOS
(
	NOMBRE_CURSO VARCHAR2(30),
	COD_CURSO NUMBER(10),
	DNI_PROFESOR VARCHAR2(9),
	MAXIMO_ALUMNOS NUMBER(2),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	NUM_HORAS NUMBER(3),
	CONSTRAINT PK_CURSOS PRIMARY KEY(COD_CURSO),
	CONSTRAINT FK_CURSOS FOREIGN KEY(DNI_PROFESOR) REFERENCES PROFESORES(DNI) ON DELETE CASCADE
);

CREATE TABLE ALUMNOS
(
	NOMBRE VARCHAR2(30),
	APELLIDO1 VARCHAR2(30), 
	APELLIDO2 VARCHAR2(30),
	DNI VARCHAR2(9),
	DIRECCION VARCHAR2(40),
	SEXO VARCHAR2(2),
	FECHA_NACIMIENTO DATE,
	CURSO NUMBER(10),
	CONSTRAINT PK_ALUMNOS PRIMARY KEY(DNI),
	CONSTRAINT FK_ALUMNOS FOREIGN KEY(CURSO) REFERENCES CURSOS(COD_CURSO) ON DELETE CASCADE,
	CONSTRAINT CHK_ALUMNOS CHECK (SEXO IN ('H', 'M'))
);

-- Parte 2
INSERT INTO PROFESORES 
VALUES ('JUAN', 'ARCH','LÓPEZ', 32432455, 'Puerta Negra 4','Ing. Informática', 7500);

INSERT INTO PROFESORES
VALUES ('MARÍA', 'OLIVA', 'RUBIO', 43215643, 'Juan Alfonso 32', 'Lda. Fil. Inglesa', 5400);

INSERT INTO CURSOS
VALUES ('Inglés Básico', 1, 43215643, 15, '01-NOV-00', '22-DEC-00', 120);

INSERT INTO CURSOS (NOMBRE_CURSO, COD_CURSO, DNI_PROFESOR, FECHA_INICIO,NUM_HORAS) 
VALUES ('Administración Linux', 2, 32432455, '01-SEP-00', 80);

INSERT INTO ALUMNOS 
VALUES ('LUCAS', 'MANILVA', 'LÓPEZ', 123523, 'ALHAMAR,3', 'H', '01-NOV-79',1);

INSERT INTO ALUMNOS (NOMBRE, APELLIDO1, APELLIDO2, DNI, DIRECCION, SEXO, CURSO)
VALUES ('ANTONIA', 'LÓPEZ', 'ALCANTARA', 2567567, 'Maniquí,21','M', 2); 

INSERT INTO ALUMNOS (NOMBRE, APELLIDO1, APELLIDO2, DNI, DIRECCION, SEXO, CURSO)
VALUES ('MANUEL', 'ALCANTARA', 'PEDRÓS', 3123689, 'Julian,2','H', 1);

INSERT INTO ALUMNOS 
VALUES ('JOSÉ', 'PÉREZ', 'CABALLAR', 4896765, 'Jarcha,5', 'H', '03-FEB-77',2);


-- Parte 3
INSERT INTO ALUMNOS (NOMBRE, APELLIDO1, APELLIDO2, DNI, SEXO, CURSO) 
VALUES ('SERGIO', 'NAVAS', 'RETAL', 1235231, 'H', 1);



-- Parte 4
UPDATE PROFESORES
SET GANA = NULL
WHERE DNI = 32432455;



-- Parte 5
INSERT INTO ALUMNOS (NOMBRE, APELLIDO1, APELLIDO2, DNI, DIRECCION, SEXO)
VALUES ('MARÍA', 'JAÉN', 'SEVILLA', 789678, 'Martos,2', 'M');



-- Parte 6
UPDATE ALUMNOS
SET FECHA_NACIMIENTO = '23-DEC-76'
WHERE DNI = 2567567;

SELECT * FROM ALUMNOS;


-- Parte 7
INSERT INTO CURSOS 
VALUES ('Programación', 5, 43215643, 20, '01-SEP-00', '01-JUL-00', 300);

UPDATE ALUMNOS 
SET CURSO = 5 
WHERE DNI = 2567567;

SELECT * FROM ALUMNOS;

-- Parte 8
INSERT INTO PROFESORES
VALUES ('LAURA', 'JIMÉNEZ', 'VÁZQUEZ', 456789, 'Puerta Verde 7','Farmacia', 4000);

SELECT * FROM PROFESORES;

DELETE FROM PROFESORES 
WHERE DNI = 456789 

-- Parte 9
DELETE FROM CURSOS
WHERE COD_CURSO = 1;

SELECT * FROM CURSOS;



-- Parte 10
ALTER TABLE CURSOS ADD NUMERO_ALUMNOS NUMBER(10);



-- Parte 11
UPDATE ALUMNOS
SET FECHA_NACIMIENTO = '01-JAN-2012'
WHERE FECHA_NACIMIENTO IS NULL;

SELECT * FROM ALUMNOS;

-- Parte 12
ALTER TABLE ALUMNOS DROP COLUMN SEXO;



-- Parte 13
UPDATE PROFESORES
SET GANA = GANA * 1.20
WHERE TITULO LIKE '%Informática';

SELECT * FROM PROFESORES;

-- Parte 14
UPDATE PROFESORES
SET DNI = 1234567
WHERE DNI = 32432455;

SELECT * FROM PROFESORES;

-- Parte 15
UPDATE PROFESORES
SET DNI = 7654321
WHERE TITULO LIKE '%Informática';


-- Parte 16
UPDATE ALUMNOS
SET SEXO = 'F'
WHERE DNI = 789678

