/*
CREATE TABLE AUDITORIA_EMPLEADOS (descripcion VARCHAR2(200));

CREATE VIEW SEDE_DEPARTAMENTOS AS
SELECT C.NUMCE, C.NOMCE, C.DIRCE,
D.NUMDE, D.NOMDE, D.PRESU, D.DIREC, D.TIDIR, D.DEPDE
FROM CENTROS C JOIN DEPARTAMENTOS D ON C.NUMCE=D.NUMCE;

INSERT INTO DEPARTAMENTOS VALUES (0, 10, 260, 'F', 10, 100, 'TEMP');




CREATE OR REPLACE TRIGGER t_empleado_in_or_del 
AFTER INSERT OR DELETE ON EMPLEADOS 
FOR EACH ROW 
BEGIN 
	
    IF INSERTING THEN 
        INSERT INTO AUDITORIA_EMPLEADOS 
        VALUES (TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI') || ' Numero empleado: ' || :NEW.NUMEM || ' Nombre empleado: ' || :NEW.NOMEM || ' Operacion: INSERT'); 

    ELSIF DELETING THEN 

        INSERT INTO AUDITORIA_EMPLEADOS 
        VALUES (TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI') || ' Numero empleado: ' || :OLD.NUMEM || ' Nombre empleado: ' || :OLD.NOMEM || ' Operacion: DELETE'); 
    END IF; 
END;



-- Inserción de datos
INSERT INTO SEDE_DEPARTAMENTOS (NUMCE, NUMDE, NOMDE)
VALUES (30, 310, 'NUEVO1');
INSERT INTO SEDE_DEPARTAMENTOS (NUMCE, NUMDE, NOMDE)
VALUES (30, 320, 'NUEVO2');
INSERT INTO SEDE_DEPARTAMENTOS (NUMCE, NUMDE, NOMDE)
VALUES (30, 330, 'NUEVO3');
SELECT * FROM CENTROS;
SELECT * FROM DEPARTAMENTOS;
-- Borrado de datos
DELETE FROM SEDE_DEPARTAMENTOS WHERE NUMDE=310;
SELECT * FROM SEDE_DEPARTAMENTOS;
DELETE FROM SEDE_DEPARTAMENTOS WHERE NUMCE=30;
SELECT * FROM SEDE_DEPARTAMENTOS;
-- Modificación de datos
UPDATE SEDE_DEPARTAMENTOS
SET NOMDE='CUENTAS', TIDIR='F', NUMCE=20 WHERE NOMDE='FINANZAS';
SELECT * FROM DEPARTAMENTOS;
UPDATE SEDE_DEPARTAMENTOS
SET NOMDE='FINANZAS', TIDIR='P', NUMCE=10 WHERE NOMDE='CUENTAS';
SELECT * FROM DEPARTAMENTOS;

*/








































