CREATE TABLE HOTEL(
    COD_HOTEL NUMBER(10),
    NOMBRE VARCHAR2(10),
    CIUDAD VARCHAR2(10),
    CONSTRAINT PK_HOTEL PRIMARY KEY (COD_HOTEL)
);

CREATE TABLE HABITACION(
    NUM_HAB NUMBER(10),
    COD_HOTEL NUMBER(10),
    TIPO VARCHAR2(10),
    PRECIO NUMBER(10,2),
    CONSTRAINT PK_HABITACION PRIMARY KEY (NUM_HAB),
    CONSTRAINT FK_HABITACION FOREIGN KEY (COD_HOTEL) REFERENCES HOTEL(COD_HOTEL),
    CONSTRAINT CHK_PRECIO CHECK (PRECIO > 30)
);

CREATE TABLE CLIENTE(
    COD_CLIENTE NUMBER(10),
    DNI VARCHAR2(10),
    NOMBRE VARCHAR2(10),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE)
);

CREATE TABLE RESERVA(
    COD_RESERVA NUMBER(10),
    COD_CLIENTE NUMBER(10),
    NUM_HAB NUMBER(10),
    FECHA_ENTRADA DATE,
    FECHA_SALIDA DATE,
    CONSTRAINT PK_RESERVA PRIMARY KEY (COD_RESERVA),
    CONSTRAINT FK_RESERVA FOREIGN KEY (NUM_HAB) REFERENCES HABITACION(NUM_HAB),
    CONSTRAINT FK2_RESERVA FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE),
    CONSTRAINT CHK_RESERVA_FECHAS CHECK (FECHA_SALIDA > FECHA_ENTRADA)
);

CREATE INDEX IDX_HOTEL_CIUDAD ON HOTEL(CIUDAD);


CREATE OR REPLACE VIEW RESERVAS_ACTIVAS AS
SELECT *
FROM RESERVA
WHERE SYSDATE BETWEEN FECHA_ENTRADA AND FECHA_SALIDA;

-- DML + TRANSACCIONES
-- Insertar datos de hoteles, habitaciones y clientes
INSERT INTO HOTEL VALUES (1, 'HotelA', 'Sevilla');
INSERT INTO HOTEL VALUES (2, 'HotelB', 'Madrid');

INSERT INTO HABITACION VALUES (101, 1, 'Doble', 50);
INSERT INTO HABITACION VALUES (102, 1, 'Suite', 80);
INSERT INTO HABITACION VALUES (201, 2, 'Individual', 40);

INSERT INTO CLIENTE VALUES (1, '12345678A', 'Joel');
INSERT INTO CLIENTE VALUES (2, '87654321B', 'Maria');

-- Crear un SAVEPOINT reserva1
SAVEPOINT reserva1;

-- Insertar una reserva correcta
INSERT INTO RESERVA VALUES (1, 1, 101, DATE '2025-01-10', DATE '2025-01-15');

-- Insertar una reserva con fechas erróneas
--INSERT INTO RESERVA VALUES (2, 1, 101, DATE '2025-02-10', DATE '2025-02-05');

-- Volver al punto de guardado reserva1
ROLLBACK TO reserva1;

-- Insertar una nueva reserva válida
INSERT INTO RESERVA VALUES (3, 2, 102, DATE '2025-03-01', DATE '2025-03-05');

-- Ejecutar COMMIT
COMMIT;

