-- Crear las tablas con claves primarias y foráneas
CREATE TABLE DEPARTAMENTO(
    COD_DEPARTAMENTO NUMBER(10),
    NOMBRE VARCHAR2(30),
    CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (COD_DEPARTAMENTO)
);

CREATE TABLE EMPLEADO(
    COD_EMPLEADO NUMBER(10),
    NOMBRE VARCHAR2(30),
    SALARIO NUMBER(10,2),
    COD_DEPARTAMENTO NUMBER(10),
    CONSTRAINT PK_EMPLEADO PRIMARY KEY (COD_EMPLEADO),
    CONSTRAINT FK_EMPLEADO_DEP FOREIGN KEY (COD_DEPARTAMENTO) REFERENCES DEPARTAMENTO(COD_DEPARTAMENTO) ON DELETE SET NULL,
    CONSTRAINT CHK_SALARIO CHECK (SALARIO >= 1000)
);

CREATE TABLE PROYECTO(
    COD_PROYECTO NUMBER(10),
    NOMBRE VARCHAR2(30),
    PRESUPUESTO NUMBER(10,2),
    CONSTRAINT PK_PROYECTO PRIMARY KEY (COD_PROYECTO),
    CONSTRAINT CHK_PRESUPUESTO CHECK (PRESUPUESTO > 0)
);

CREATE TABLE ASIGNACION(
    COD_EMPLEADO NUMBER(10),
    COD_PROYECTO NUMBER(10),
    HORAS NUMBER(10),
    CONSTRAINT PK_ASIGNACION PRIMARY KEY (COD_EMPLEADO, COD_PROYECTO),
    CONSTRAINT FK_ASIG_EMP FOREIGN KEY (COD_EMPLEADO) REFERENCES EMPLEADO(COD_EMPLEADO),
    CONSTRAINT FK_ASIG_PROY FOREIGN KEY (COD_PROYECTO) REFERENCES PROYECTO(COD_PROYECTO)
);

-- Crear un índice sobre salario
CREATE INDEX IDX_EMPLEADO_SALARIO ON EMPLEADO(SALARIO);

-- Crear una vista con empleados y su departamento
CREATE OR REPLACE VIEW EMPLEADOS_DEPARTAMENTOS AS
SELECT E.COD_EMPLEADO, E.NOMBRE AS EMPLEADO, E.SALARIO,
       D.NOMBRE AS DEPARTAMENTO
FROM EMPLEADO E
LEFT JOIN DEPARTAMENTO D ON E.COD_DEPARTAMENTO = D.COD_DEPARTAMENTO;

-- DDL + TRANSACCIONES
-- Insertar departamentos, empleados y proyectos
INSERT INTO DEPARTAMENTO VALUES (1, 'Informatica');
INSERT INTO DEPARTAMENTO VALUES (2, 'Marketing');

INSERT INTO EMPLEADO VALUES (1, 'Joel', 1500, 1);
INSERT INTO EMPLEADO VALUES (2, 'Maria', 2000, 1);
INSERT INTO EMPLEADO VALUES (3, 'Luis', 1200, 2);

INSERT INTO PROYECTO VALUES (1, 'ProyectoA', 50000);
INSERT INTO PROYECTO VALUES (2, 'ProyectoB', 30000);

-- Crear un SAVEPOINT asignaciones
SAVEPOINT asignaciones;

-- Asignar empleados a proyectos
INSERT INTO ASIGNACION VALUES (1, 1, 20);
INSERT INTO ASIGNACION VALUES (2, 1, 15);
INSERT INTO ASIGNACION VALUES (3, 2, 10);

-- Reducir el presupuesto de un proyecto a valor negativo
UPDATE PROYECTO SET PRESUPUESTO = -500 WHERE COD_PROYECTO = 1;

-- Recuperar los datos
ROLLBACK TO asignaciones;

-- Corregir el presupuesto
UPDATE PROYECTO SET PRESUPUESTO = 40000 WHERE COD_PROYECTO = 1;

-- Confirmar los cambios
COMMIT;

--SELECT * FROM DEPARTAMENTO;
--SELECT * FROM EMPLEADO;
--SELECT * FROM PROYECTO;
--SELECT * FROM ASIGNACION;
