DROP TABLE EMPLEADOS CASCADE CONSTRAINTS;

DROP TABLE EMPLEADOS_BAJA CASCADE CONSTRAINTS;


CREATE TABLE EMPLEADOS(
DNI VARCHAR2(9) PRIMARY KEY,
NOMEMP VARCHAR2(50),
JEFE VARCHAR2(9),
DEPARTAMENTO NUMBER,
SALARIO NUMBER(9,2) DEFAULT 1000,
USUARIO VARCHAR2(50),
FECHA DATE,
CONSTRAINT FK_JEFE FOREIGN KEY (JEFE) REFERENCES EMPLEADOS (DNI) );

INSERT INTO EMPLEADOS VALUES ('JEF000001','JEFE',NULL,10,2000,USER,SYSDATE);
INSERT INTO EMPLEADOS VALUES ('E1','EMPLEADO1','JEF000001',10,1000,USER,SYSDATE);
INSERT INTO EMPLEADOS VALUES ('E2','EMPLEADO2','JEF000001',10,1000,USER,SYSDATE);
INSERT INTO EMPLEADOS VALUES ('E3','EMPLEADO3','JEF000001',10,1000,USER,SYSDATE);
INSERT INTO EMPLEADOS VALUES ('E4','EMPLEADO4','JEF000001',10,1000,USER,SYSDATE);
INSERT INTO EMPLEADOS VALUES ('E5','EMPLEADO5','JEF000001',10,1000,USER,SYSDATE);

INSERT INTO EMPLEADOS VALUES ('SAL1','SALARIO1',NULL,10,1000,USER,SYSDATE);

INSERT INTO EMPLEADOS VALUES ('BAJA1','Empleado Baja',NULL,10,1200,USER,SYSDATE);




-- SOLICITADO EN EJER3
CREATE TABLE EMPLEADOS_BAJA(
DNI VARCHAR2(9) PRIMARY KEY,
NOMEMP VARCHAR2(50),
JEFE VARCHAR2(9),
DEPARTAMENTO NUMBER,
SALARIO NUMBER(9,2) DEFAULT 1000,
USUARIO VARCHAR2(50),
FECHA DATE );



/* Ejercicio 1:
Crear un trigger sobre la tabla EMPLEADOS para que no se permita que un empleado
sea jefe de más de cinco empleados. */
CREATE OR REPLACE TRIGGER TRG_MAX_SUBORDINADOS
BEFORE INSERT OR UPDATE OF JEFE ON EMPLEADOS
FOR EACH ROW
DECLARE
    V_TOTAL NUMBER;
BEGIN
    IF :NEW.JEFE IS NOT NULL THEN
        SELECT COUNT(*)
        INTO V_TOTAL
        FROM EMPLEADOS
        WHERE JEFE = :NEW.JEFE;

        -- Si es UPDATE y el jefe no cambia, no contamos al propio empleado dos veces
        IF UPDATING AND :OLD.JEFE = :NEW.JEFE THEN
            V_TOTAL := V_TOTAL - 1;
        END IF;

        IF V_TOTAL >= 5 THEN
            RAISE_APPLICATION_ERROR(-20001,
                'Este jefe ya tiene 5 empleados a su cargo');
        END IF;
    END IF;
END;

-- TEST 6º EMP
INSERT INTO EMPLEADOS VALUES ('E6','EMPLEADO6','JEF000001',10,1000,USER,SYSDATE);

-- ACTUALZIAR A UN JEFE CON 5 EMPLEADOS
INSERT INTO EMPLEADOS VALUES ('E7','EMPLEADO7',NULL,10,1000,USER,SYSDATE);

UPDATE EMPLEADOS SET JEFE = 'JEF000001' WHERE DNI = 'E7';





/* Ejercicio 2:
Crear un trigger para impedir que se aumente el salario de un empleado en más de un
20%. */
CREATE OR REPLACE TRIGGER TRG_LIMITE_SUBIDA_SALARIO
BEFORE UPDATE OF SALARIO ON EMPLEADOS
FOR EACH ROW
BEGIN
    IF :NEW.SALARIO > :OLD.SALARIO * 1.20 THEN
        RAISE_APPLICATION_ERROR(-20002,
            'No se permite aumentar el salario más de un 20%');
    END IF;
END;

-- TEST 
UPDATE EMPLEADOS SET SALARIO = 1300 WHERE DNI = 'SAL1';




/* Ejercicio 3:
Crear un trigger que inserte una fila en la tabla empleados_baja cuando se borre una fila
en la tabla empleados. Los datos que se insertan son los del empleado que se da de baja
en la tabla empleados, salvo en las columnas usuario y fecha se grabarán las variables
del sistema USER y SYSDATE que almacenan el usuario y fecha actual */
CREATE OR REPLACE TRIGGER TRG_EMPLEADO_BAJA
BEFORE DELETE ON EMPLEADOS
FOR EACH ROW
BEGIN
    INSERT INTO EMPLEADOS_BAJA
    (DNI, NOMEMP, JEFE, DEPARTAMENTO, SALARIO, USUARIO, FECHA)
    VALUES
    (:OLD.DNI, :OLD.NOMEMP, :OLD.JEFE, :OLD.DEPARTAMENTO,
     :OLD.SALARIO, USER, SYSDATE);
END;

DELETE FROM EMPLEADOS WHERE DNI = 'BAJA1';

SELECT * FROM EMPLEADOS_BAJA WHERE DNI = 'BAJA1';







