--- Base de datos tablas

CREATE TABLE ALUMNO (
    COD_ALUMNO NUMBER(10),
    DNI        VARCHAR2(15),
    NOMBRE     VARCHAR2(30),
    APELLIDO   VARCHAR2(30),
    CONSTRAINT PK_ALUMNO PRIMARY KEY (COD_ALUMNO),
    CONSTRAINT UK_ALU_DNI UNIQUE (DNI)
);

CREATE TABLE PROFESOR (
    COD_PROFESOR NUMBER(10),
    NOMBRE       VARCHAR2(30),
    APELLIDO     VARCHAR2(30),
    CONSTRAINT PK_PROFESOR PRIMARY KEY (COD_PROFESOR)
);

CREATE TABLE TITULACION (
    COD_TITULACION NUMBER(10),
    NOMBRE         VARCHAR2(50),
    CONSTRAINT PK_TITULACION PRIMARY KEY (COD_TITULACION)
);

CREATE TABLE ASIGNATURA (
    COD_ASIGNATURA NUMBER(10),
    NOMBRE         VARCHAR2(50),
    PRECIO         NUMBER(10,2),
    COD_TITULACION NUMBER(10),
    COD_PROFESOR   NUMBER(10),
    CONSTRAINT PK_ASIGNATURA PRIMARY KEY (COD_ASIGNATURA),
    CONSTRAINT FK_ASIG_TITU FOREIGN KEY (COD_TITULACION) REFERENCES TITULACION(COD_TITULACION),
    CONSTRAINT FK_ASIG_PROF FOREIGN KEY (COD_PROFESOR) REFERENCES PROFESOR(COD_PROFESOR)
);

CREATE TABLE MATRICULA (
    COD_MATRICULA  NUMBER(10),
    COD_ALUMNO     NUMBER(10),
    COD_ASIGNATURA NUMBER(10),
    CONSTRAINT PK_MATRICULA PRIMARY KEY (COD_MATRICULA),
    CONSTRAINT FK_MATRI_ALU FOREIGN KEY (COD_ALUMNO) REFERENCES ALUMNO(COD_ALUMNO),
    CONSTRAINT FK_MATRI_ASIG FOREIGN KEY (COD_ASIGNATURA) REFERENCES ASIGNATURA(COD_ASIGNATURA)
);

CREATE TABLE IMPARTE (
    COD_PROFESOR   NUMBER(10),
    COD_ASIGNATURA NUMBER(10),
    CONSTRAINT FK_IMP_PROF FOREIGN KEY (COD_PROFESOR) REFERENCES PROFESOR(COD_PROFESOR),
    CONSTRAINT FK_IMP_ASIG FOREIGN KEY (COD_ASIGNATURA) REFERENCES ASIGNATURA(COD_ASIGNATURA)
);


CREATE SEQUENCE SEQ_ALUMNO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROFESOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TITULACION START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ASIGNATURA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MATRICULA START WITH 1 INCREMENT BY 1;


/* Realizar un procedure que se llame insertar_alumno, que recibirá como
parámetro el nombre y apellido de una persona, e inserte de forma
automática esa persona como alumno. */

CREATE OR REPLACE PROCEDURE INSERTAR_ALUMNO(
    V_NOMBRE   VARCHAR2,
    V_APELLIDO VARCHAR2
) IS
CONTADOR NUMBER;
EXISTE EXCEPTION;
BEGIN
	SELECT COUNT(*) INTO CONTADOR FROM ALUMNO A 
	WHERE A.NOMBRE=V_NOMBRE
		AND A.APELLIDO=V_APELLIDO;

	IF CONTADOR = 0 THEN
	    INSERT INTO ALUMNO (COD_ALUMNO, NOMBRE, APELLIDO)
	    VALUES (SEQ_ALUMNO.NEXTVAL, V_NOMBRE, V_APELLIDO);
	ELSE 
		RAISE EXISTE;
	END IF;

	EXCEPTION
		WHEN EXISTE THEN
		DBMS_OUTPUT.PUT_LINE('USUARIO ' || V_NOMBRE || ' YA EXISTE');
END;

BEGIN
	INSERTAR_ALUMNO('Marta','Lopez');
END;


SELECT * FROM ALUMNO;



/* Realizar una función que reciba como parámetro el nombre y el apellido
de una persona, también debe recibir un parámetro que podrá ser un 1
(en ese caso debe insertarlo como un alumno) o un 2 (debe insertarlo
como profesor), y un parámetro de entrada salida en el que deberá
devolver el código del profesor o alumno insertado. La función deberá
devolver un 1 si se ha podido realizar la inserción, y un cero si ha
ocurrido algún error. */

CREATE OR REPLACE FUNCTION INSERTAR_PERSONA(
    V_NOMBRE   VARCHAR2,
    V_APELLIDO VARCHAR2,
    V_TIPO     NUMBER,
    V_CODIGO   IN OUT NUMBER
) RETURN NUMBER
IS
    CONTADOR NUMBER;
    YA_EXISTE EXCEPTION;
	RESULTADO NUMBER;
BEGIN
	RESULTADO:=0;

    -- INSERTAR ALUMNO
    IF V_TIPO = 1 THEN

        -- EXISTE?
        SELECT COUNT(*) INTO CONTADOR FROM ALUMNO
        WHERE NOMBRE = V_NOMBRE
        	AND APELLIDO = V_APELLIDO;

        -- NO EXISTE, LO CREO
        IF CONTADOR = 0 THEN
	        V_CODIGO := SEQ_ALUMNO.NEXTVAL;
	
	        -- INSERTAR
	        INSERT INTO ALUMNO (COD_ALUMNO, NOMBRE, APELLIDO)
	        VALUES (V_CODIGO, V_NOMBRE, V_APELLIDO);
		ELSE
			RAISE YA_EXISTE;
        END IF;
        
        RESULTADO:=1;


     -- INSERTAR PROFESOR
    ELSIF V_TIPO = 2 THEN

        -- EXISTE?
        SELECT COUNT(*) INTO CONTADOR
        FROM PROFESOR
        WHERE NOMBRE = V_NOMBRE
        	AND APELLIDO = V_APELLIDO;

        -- NO EXISTE, LO CREO
        IF CONTADOR = 0 THEN
	        -- GENERAR CÓDIGO CON SECUENCIA
	        V_CODIGO := SEQ_PROFESOR.NEXTVAL;
	
	        -- INSERTAR
	        INSERT INTO PROFESOR (COD_PROFESOR, NOMBRE, APELLIDO)
	        VALUES (V_CODIGO, V_NOMBRE, V_APELLIDO);
		ELSE
			RAISE YA_EXISTE;
        END IF;

        RESULTADO:=1;

    END IF;
    RETURN RESULTADO;


EXCEPTION
    WHEN YA_EXISTE THEN
        DBMS_OUTPUT.PUT_LINE('USUARIO ' || V_NOMBRE || ' YA EXISTE');
        RETURN RESULTADO;

    WHEN OTHERS THEN
        RETURN RESULTADO;
        
END;

-- PRUEBA inserta alumno
DECLARE
	COD NUMBER := 0;
	PRUEBA NUMBER;
BEGIN
    PRUEBA := INSERTAR_PERSONA('Maria', 'a', 1, COD);
END;

-- PRUEBA inserta profe
DECLARE
	COD NUMBER := 0;
	PRUEBA NUMBER;
BEGIN
    PRUEBA := INSERTAR_PERSONA('Josefa', 'Perez', 2, COD);
	DBMS_OUTPUT.PUT_LINE(COD || '  ' || PRUEBA);
END;

-- PRUEBA REPETIDA
DECLARE
	COD NUMBER := 0;
	PRUEBA NUMBER;
BEGIN
    PRUEBA := INSERTAR_PERSONA('Encarnita', 'Perez', 2, COD);
	DBMS_OUTPUT.PUT_LINE(COD || '  ' || PRUEBA);
END;

SELECT * FROM ALUMNO a;
SELECT * FROM PROFESOR p;




/* Realizar una función que devuelva un uno o un cero, si el alumno con
dni que se le pasa como argumento está matriculado en la asignatura
cuyo nombre se le pasa también como argumento. La función también
deberá tener un parámetro de entrada salida en donde se devuelva el
nombre y apellido del profesor que le da clase en esa asignatura, si el
alumno está matriculado. Procedure o bloque anónimo para comprobar que
funciona. */

CREATE OR REPLACE FUNCTION ESTA_MATRICULADO(
    V_DNI        VARCHAR2,
    V_ASIG       VARCHAR2,
    V_PROFESOR   IN OUT VARCHAR2
) RETURN NUMBER
IS
    CONTADOR  NUMBER;
    DEVUELVE  NUMBER := 0;
BEGIN
    -- ESTÁ MATRICULADO?
    SELECT COUNT(*) INTO CONTADOR
    FROM ALUMNO A
    JOIN MATRICULA M ON A.COD_ALUMNO = M.COD_ALUMNO
    JOIN ASIGNATURA S ON M.COD_ASIGNATURA = S.COD_ASIGNATURA
    WHERE A.DNI = V_DNI
      AND UPPER(S.NOMBRE) = UPPER(V_ASIG);

    IF CONTADOR > 0 THEN
        -- SI ESTÁ MATRICULADO, SACAR PROFESOR
        SELECT P.NOMBRE || ' ' || P.APELLIDO
        INTO V_PROFESOR
        FROM PROFESOR P
        JOIN IMPARTE I ON P.COD_PROFESOR = I.COD_PROFESOR
        JOIN ASIGNATURA S ON I.COD_ASIGNATURA = S.COD_ASIGNATURA
        WHERE UPPER(S.NOMBRE) = UPPER(V_ASIG);

        DEVUELVE := 1;
    END IF;

    RETURN DEVUELVE;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
    WHEN OTHERS THEN
        RETURN 0;
END;


-- PRUEBA ALUMNO MATRICULADO
DECLARE
    PROF VARCHAR2(100);
    R NUMBER;
BEGIN
    PROF := '';

    R := ESTA_MATRICULADO('12345678A', 'BASES DE DATOS', PROF);

    DBMS_OUTPUT.PUT_LINE('RESULTADO: ' || R);
    DBMS_OUTPUT.PUT_LINE('PROFESOR: ' || PROF);
END;

-- PRUEBA NO MATRICULADO EN ASIGNATURA
DECLARE
    PROF VARCHAR2(100);
    R NUMBER;
BEGIN
    PROF := '';

    R := ESTA_MATRICULADO('12345678A', 'PROGRAMACIÓN', PROF);

    DBMS_OUTPUT.PUT_LINE('RESULTADO: ' || R);

    IF R = 1 THEN
        DBMS_OUTPUT.PUT_LINE('PROFESOR: ' || PROF);
    END IF;
END;


-- ALUMNO NO EXISTE
DECLARE
    PROF VARCHAR2(100);
    R NUMBER;
BEGIN
    PROF := '';

    R := ESTA_MATRICULADO('99999999Z', 'BASES DE DATOS', PROF);

    DBMS_OUTPUT.PUT_LINE('RESULTADO: ' || R);

    IF R = 1 THEN
        DBMS_OUTPUT.PUT_LINE('PROFESOR: ' || PROF);
    END IF;
END;




/* Realizar una función que devuelva un 1 si el nombre y apellido de la
persona que se le pasa por parámetro es un alumno, un dos si es un
profesor y un 0 si no está en la base de datos. */

CREATE OR REPLACE FUNCTION QUE_ES(
    V_NOMBRE   VARCHAR2,
    V_APELLIDO VARCHAR2
) RETURN NUMBER
IS
    CONTADOR NUMBER;
    RESULTADO NUMBER := 0;
BEGIN
    -- ES ALUMNO?
    SELECT COUNT(*) INTO CONTADOR
    FROM ALUMNO
    WHERE UPPER(NOMBRE) = UPPER(V_NOMBRE)
      AND UPPER(APELLIDO) = UPPER(V_APELLIDO);

	-- SI ME DA ALGO LA SELECT, ES QUE SI ES ALUMNO
    IF CONTADOR > 0 THEN
        RESULTADO := 1;
    ELSE
        -- ES PROFESOR?
        SELECT COUNT(*) INTO CONTADOR
        FROM PROFESOR
        WHERE UPPER(NOMBRE) = UPPER(V_NOMBRE)
          AND UPPER(APELLIDO) = UPPER(V_APELLIDO);

		-- SI ME DA ALGO LA SELECT, ES QUE SI ES PROFE
        IF CONTADOR > 0 THEN
            RESULTADO := 2;
        END IF;
    END IF;

    RETURN RESULTADO;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END;


/* Crear un procedure que reciba como parámetro el nombre de una
titulación, el nombre de la asignatura, y el nombre y apellido del
profesor (en dos parámetros distintos), y que inserte esos datos en la
tabla de asignatura. Si se produce un error notificarlo. Los errores
que deben notificarse son:
	• No existe la titulación
	• No existe la personas
	• La persona no es un profesor
	• El nombre de la asignatura ya está en la base de datos. */

CREATE OR REPLACE PROCEDURE INSERTAR_ASIGNATURA(
    V_TITULACION VARCHAR2,
    V_ASIGNATURA VARCHAR2,
    V_NOMBRE     VARCHAR2,
    V_APELLIDO   VARCHAR2
)
IS
    COD_TITU NUMBER;
    COD_PROF NUMBER;
    CONTADOR NUMBER;
BEGIN
    -- EXISTE LA TITULACIÓN?
    SELECT COUNT(*) INTO CONTADOR
    FROM TITULACION
    WHERE UPPER(NOMBRE) = UPPER(V_TITULACION);

    IF CONTADOR = 0 THEN
        DBMS_OUTPUT.PUT_LINE('NO EXISTE LA TITULACIÓN');
        RETURN;
    ELSE
    	SELECT COD_TITULACION INTO COD_TITU
    	FROM TITULACION
    	WHERE UPPER(NOMBRE) = UPPER(V_TITULACION);
    END IF;

    -- EXISTE LA PERSONA COMO PROFESOR?
    SELECT COUNT(*) INTO CONTADOR
    FROM PROFESOR
    WHERE UPPER(NOMBRE) = UPPER(V_NOMBRE)
      AND UPPER(APELLIDO) = UPPER(V_APELLIDO);

    IF CONTADOR = 0 THEN
        -- y como alumno?
        SELECT COUNT(*) INTO CONTADOR
        FROM ALUMNO
        WHERE UPPER(NOMBRE) = UPPER(V_NOMBRE)
          AND UPPER(APELLIDO) = UPPER(V_APELLIDO);

        IF CONTADOR = 0 THEN
            DBMS_OUTPUT.PUT_LINE('LA PERSONA NO EXISTE');
        ELSE
            DBMS_OUTPUT.PUT_LINE('NO ES PROFESOR');
        END IF;

        RETURN;
    END IF;

    -- Obtener código del profesor para el insert y no salte el problemita del FK
    SELECT COD_PROFESOR INTO COD_PROF
    FROM PROFESOR
    WHERE UPPER(NOMBRE) = UPPER(V_NOMBRE)
      AND UPPER(APELLIDO) = UPPER(V_APELLIDO);

    -- YA EXISTE LA ASIGNATURA?
    SELECT COUNT(*) INTO CONTADOR
    FROM ASIGNATURA
    WHERE UPPER(NOMBRE) = UPPER(V_ASIGNATURA);

    IF CONTADOR > 0 THEN
        DBMS_OUTPUT.PUT_LINE('YA EXISTE LA ASIGNATURA');
        RETURN;
    END IF;

    -- INSERTAR ASIGNATURA
    INSERT INTO ASIGNATURA (COD_ASIGNATURA, NOMBRE, PRECIO, COD_TITULACION, COD_PROFESOR)
    VALUES (SEQ_ASIGNATURA.NEXTVAL, V_ASIGNATURA, 0, COD_TITU, COD_PROF);

    DBMS_OUTPUT.PUT_LINE('ASIGNATURA INSERTADA CORRECTAMENTE');

EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR DESCONOCIDO: ' || SQLERRM);
END;

-- PRUEBA DE QUE TODO SE INSERTA BIEN
-- INSERTAR DATOS
INSERT INTO TITULACION VALUES (SEQ_TITULACION.NEXTVAL, 'INFORMATICA');
INSERT INTO TITULACION VALUES (SEQ_TITULACION.NEXTVAL, 'ADMINISTRACION');

INSERT INTO PROFESOR VALUES (SEQ_PROFESOR.NEXTVAL, 'Antonio', 'Gomez');
INSERT INTO PROFESOR VALUES (SEQ_PROFESOR.NEXTVAL, 'Maria', 'Lopez');

INSERT INTO ALUMNO VALUES (SEQ_ALUMNO.NEXTVAL, '123A', 'Pepe', 'Ruiz');
INSERT INTO ALUMNO VALUES (SEQ_ALUMNO.NEXTVAL, '456B', 'Juan', 'Perez');

-- PRUEBA
BEGIN
    INSERTAR_ASIGNATURA('INFORMATICA', 'PROGRAMACION', 'Antonio', 'Gomez');
END;

-- PRUEBA NO EXISTE LA TITULACIÓN
BEGIN
    INSERTAR_ASIGNATURA('BIOLOGIA', 'PROGRAMACION', 'Antonio', 'Gomez');
END;

--PRUEBA PERSONA NO EXISTE
BEGIN
    INSERTAR_ASIGNATURA('INFORMATICA', 'PROGRAMACION', 'Roberto', 'Martinez');
END;

-- PRUEBA NO ES PROFESOR
BEGIN
    INSERTAR_ASIGNATURA('INFORMATICA', 'PROGRAMACION', 'Pepe', 'Ruiz');
END;

-- YA EXISTE LA ASIGNATURA
BEGIN
    INSERTAR_ASIGNATURA('INFORMATICA', 'BASE DE DATOS', 'Antonio', 'Gomez');
END;

























