CREATE TABLE MUNICIPIO(
    ID NUMBER(10),
    NOMBRE VARCHAR2(50) NOT NULL,
    COD_POSTAL VARCHAR2(10),
    PROVINCIA VARCHAR2(50),
    CONSTRAINT PK_MUNICIPIO PRIMARY KEY (ID)
);

CREATE TABLE VIVIENDA(
    ID NUMBER(10),
    TIPO_VIA VARCHAR2(20) DEFAULT 'Calle',
    NOMBRE_VIA VARCHAR2(50) NOT NULL,
    NUMERO NUMBER(5) NOT NULL,
    ID_MUNICIPIO NUMBER(10),
    CONSTRAINT PK_VIVIENDA PRIMARY KEY (ID),
    CONSTRAINT FK_VIVIENDA FOREIGN KEY (ID_MUNICIPIO) REFERENCES MUNICIPIO(ID)
);

CREATE TABLE PERSONA(
    DNI VARCHAR2(9),
    NOMBRE VARCHAR2(50) NOT NULL,
    FECHA_NAC DATE,
    SEXO VARCHAR2(1),
    ID_VIVIENDA NUMBER(10),
    CONSTRAINT PK_PERSONA PRIMARY KEY (DNI),
    CONSTRAINT FK_PERSONA FOREIGN KEY (ID_VIVIENDA) REFERENCES VIVIENDA(ID),
    CONSTRAINT CHK_SEXO CHECK (SEXO IN ('H','M'))
);

CREATE TABLE CABEZA_FAMILIA(
    DNI VARCHAR2(9),
    ID_VIVIENDA NUMBER(10),
    CONSTRAINT PK_CABEZA_FAMILIA PRIMARY KEY (DNI),
    CONSTRAINT FK_CABEZA_FAMILIA FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
    CONSTRAINT FK2_CABEZA_FAMILIA FOREIGN KEY (ID_VIVIENDA) REFERENCES VIVIENDA(ID),
    CONSTRAINT UQ_CABEZA_FAMILIA UNIQUE (ID_VIVIENDA)

);

CREATE TABLE POSEE(
    DNI VARCHAR2(9),
    ID_VIVIENDA NUMBER(10),
    CONSTRAINT PK_POSEE PRIMARY KEY (DNI, ID_VIVIENDA),
    CONSTRAINT FK_POSEE FOREIGN KEY (DNI) REFERENCES PERSONA(DNI),
    CONSTRAINT FK2_POSEE FOREIGN KEY (ID_VIVIENDA) REFERENCES VIVIENDA(ID)
);