CREATE TABLE SUCURSAL(
CODIGO NUMBER (10) NOT NULL,
DIRECCION VARCHAR2 (100),
TELEFONO NUMBER (9),
CONSTRAINT PK_SUCURSAL PRIMARY KEY (CODIGO)
);

CREATE TABLE EMPLEADO(
DNI VARCHAR2 (9) NOT NULL,
NOMBRE VARCHAR2 (20) NOT NULL,
DIRECCION VARCHAR2 (100),
TELEFONO NUMBER (9),
SUCURSAL NUMBER (10),
CONSTRAINT PK_EMPLEADO PRIMARY KEY (DNI),
CONSTRAINT FK_EMPLEADO FOREIGN KEY (SUCURSAL) REFERENCES SUCURSAL(CODIGO)
);

CREATE TABLE REVISTA(
NUM_REG NUMBER (10) NOT NULL,
TITULO VARCHAR2 (100) NOT NULL,
PERIODICIDAD VARCHAR2(20) DEFAULT 'Mensual',
TIPO VARCHAR2 (10),
SUCURSAL NUMBER (10),
CONSTRAINT PK_REVISTA PRIMARY KEY (NUM_REG),
CONSTRAINT FK_REVISTA FOREIGN KEY (SUCURSAL) REFERENCES SUCURSAL(CODIGO),
CONSTRAINT CHK_PERIODICIDAD CHECK(PERIODICIDAD IN ('Semanal','Quincenal','Mensual','Trimestral','Anual'))
);

CREATE TABLE PERIODISTA(
DNI VARCHAR2 (9) NOT NULL,
NOMBRE VARCHAR2 (20) NOT NULL,
DIRECCION VARCHAR2 (100),
TELEFONO NUMBER (9),
ESPECIALIDAD VARCHAR2 (25),
CONSTRAINT PK_PERIODISTA PRIMARY KEY (DNI)
);

CREATE TABLE ESCRIBE(
NUM_REG NUMBER (10) NOT NULL,
DNI_PER VARCHAR2 (9) NOT NULL,
CONSTRAINT PK_ESCRIBE PRIMARY KEY (NUM_REG, DNI_PER),
CONSTRAINT FK_ESCRIBE FOREIGN KEY (NUM_REG) REFERENCES REVISTA(NUM_REG),
CONSTRAINT FK2_ESCRIBE FOREIGN KEY (DNI_PER) REFERENCES PERIODISTA(DNI)
);

CREATE TABLE NUM_REVISTA(
NUM_REG NUMBER (10) NOT NULL,
NUMERO NUMBER (15) NOT NULL,
NUMPAGINAS NUMBER(3) DEFAULT 1,
FECHA DATE,
CANT_VENDIDAS NUMBER (10),
CONSTRAINT PK_NUM_REVISTA PRIMARY KEY (NUM_REG, NUMERO),
CONSTRAINT FK_NUM_REVISTA FOREIGN KEY (NUM_REG) REFERENCES REVISTA(NUM_REG)
);



