CREATE TABLE ALUMNO
(
    NUMMATRICULA VARCHAR2(10),
    NOMBRE VARCHAR2(50),
    FECHANACIMIENTO DATE,
    TELEFONO VARCHAR2(15),
    CONSTRAINT PK_ALUMNO PRIMARY KEY (NUMMATRICULA)
);

CREATE TABLE PROFESOR
(
    IDPROFESOR VARCHAR2(10),
    NIF_P VARCHAR2(10),
    NOMBRE VARCHAR2(50),
    ESPECIALIDAD VARCHAR2(50),
    TELEFONO VARCHAR2(15),
    CONSTRAINT PK_PROFESOR PRIMARY KEY (IDPROFESOR),
    CONSTRAINT UQ_NIF_PROFESOR UNIQUE (NIF_P)
);

CREATE TABLE ASIGNATURA
(
    CODASIGNATURA VARCHAR2(10),
    NOMBRE VARCHAR2(50),
    IDPROFESOR VARCHAR2(10),
    CONSTRAINT PK_ASIGNATURA PRIMARY KEY (CODASIGNATURA),
    CONSTRAINT FK1_ASIGNATURA FOREIGN KEY (IDPROFESOR)
        REFERENCES PROFESOR(IDPROFESOR)
);

CREATE TABLE RECIBE
(
    NUMMATRICULA VARCHAR2(10),
    CODASIGNATURA VARCHAR2(10),
    CURSOESCOLAR VARCHAR2(9),
    CONSTRAINT PK_RECIBE PRIMARY KEY (NUMMATRICULA, CODASIGNATURA, CURSOESCOLAR),
    CONSTRAINT FK1_RECIBE FOREIGN KEY (NUMMATRICULA)
        REFERENCES ALUMNO(NUMMATRICULA),
    CONSTRAINT FK2_RECIBE FOREIGN KEY (CODASIGNATURA)
        REFERENCES ASIGNATURA(CODASIGNATURA)
);