CREATE TABLE EDITORIAL(
    COD_EDITORIAL NUMBER(10),
    DENOMINACION VARCHAR2(100),
    CONSTRAINT EDITORIAL_PK PRIMARY KEY(COD_EDITORIAL)
);

CREATE TABLE TEMA(
    COD_TEMA NUMBER(10),
    DENOMINACION VARCHAR2(100),
    COD_TEMA_PADRE NUMBER(10) CHECK(COD_TEMA_PADRE >= COD_TEMA),
    CONSTRAINT TEMA_PK PRIMARY KEY(COD_TEMA),
    CONSTRAINT TEMA_FK FOREIGN KEY(COD_TEMA_PADRE) REFERENCES TEMA(COD_TEMA)
);

CREATE TABLE LIBRO(
    COD_LIBRO NUMBER(10),
    TITULO VARCHAR2(100),
    F_CREACION DATE,
    COD_TEMA  NUMBER(10),
    AUTOR_PRINCIPAL NUMBER(10),
    CONSTRAINT LIBRO_PK PRIMARY KEY(COD_LIBRO),
    CONSTRAINT LIBRO_FK FOREIGN KEY(COD_TEMA) REFERENCES TEMA(COD_TEMA)
);

CREATE TABLE AUTOR(
    COD_AUTOR NUMBER(10),
    NOMBRE VARCHAR2(100),
    F_NACIMIENTO DATE,
    LIBRO_PRINCIPAL NUMBER(10),
    SEXO VARCHAR2(1),
    CONSTRAINT AUTOR_PK PRIMARY KEY(COD_AUTOR),
    CONSTRAINT AUTOR_FK FOREIGN KEY(LIBRO_PRINCIPAL) REFERENCES LIBRO(COD_LIBRO)
);

CREATE TABLE LIBRO_AUTOR(
    COD_LIBRO NUMBER(10),
    COD_AUTOR NUMBER(10),
    ORDEN NUMBER(1) CHECK(ORDEN BETWEEN 1 AND 5),
    CONSTRAINT LIBRO_AUTOR_PK PRIMARY KEY(COD_LIBRO, COD_AUTOR),
    CONSTRAINT LIBRO_AUTOR_FK_1 FOREIGN KEY(COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
    CONSTRAINT LIBRO_AUTOR_FK_2 FOREIGN KEY(COD_AUTOR) REFERENCES AUTOR(COD_AUTOR)
);

CREATE TABLE PUBLICACIONES(
    COD_EDITORIAL NUMBER(10),
    COD_LIBRO NUMBER(10),
    PRECIO NUMBER(10,2) NOT NULL CHECK(PRECIO > 0),
    F_PUBLICACION DATE DEFAULT SYSDATE,
    CONSTRAINT PUBLICACIONES_PK PRIMARY KEY(COD_EDITORIAL, COD_LIBRO),
    CONSTRAINT PUBLICACIONES_FK_1 FOREIGN KEY(COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
    CONSTRAINT PUBLICACIONES_FK_2 FOREIGN KEY(COD_EDITORIAL) REFERENCES EDITORIAL(COD_EDITORIAL) on delete cascade
);

ALTER TABLE LIBRO ADD CONSTRAINT LIBRO_FK_2 FOREIGN KEY (AUTOR_PRINCIPAL) REFERENCES AUTOR(COD_AUTOR);

--ejer7
ALTER TABLE PUBLICACIONES DROP CONSTRAINT PUBLICACIONES_PK;

ALTER TABLE PUBLICACIONES ADD CONSTRAINT PUBLICACIONES_PK PRIMARY KEY (COD_EDITORIAL, COD_LIBRO, F_PUBLICACION);


--ejer8
ALTER TABLE AUTOR ADD CONSTRAINT AUTOR_SEXO_CHECK CHECK (SEXO IN ('H', 'M'));

--ejer9
ALTER TABLE LIBRO ADD CONSTRAINT LIBRO_COD_FORMATO_CHECK 
    CHECK (REGEXP_LIKE(TO_CHAR(COD_LIBRO), '^[0-9][A-Z]{5}-[A-Z0-9]{5}$'));

--ejer10
ALTER TABLE AUTOR ADD CONSTRAINT AUTOR_NOMBRE_FORMATO_CHECK 
    CHECK (NOMBRE = INITCAP(NOMBRE));

--ejer11
ALTER TABLE LIBRO ADD CONSTRAINT LIBRO_FECHA_VACACIONES_CHECK 
    CHECK (TO_CHAR(F_CREACION, 'MMDD') NOT BETWEEN '0715' AND '0815');

--ejer12
DROP TABLE PUBLICACIONES, LIB_AUTOR, LIBRO, AUTOR, TEMA, EDITORIAL CASCADE CONSTRAINTS;
