CREATE TABLE VEHICULO(
    MATRICULA VARCHAR2(7),
    MARCA VARCHAR2(10) NOT NULL,
    MODELO VARCHAR2(10) NOT NULL,
    FECHA_COMPRA DATE,
    PRECIO_DIA NUMBER(10,2),
    CONSTRAINT PK1_VEHICULO PRIMARY KEY (MATRICULA),
    CONSTRAINT CHK_VEHICULO CHECK (PRECIO_DIA > 0),
    CONSTRAINT CHK2_VEHICULO CHECK (FECHA_COMPRA >= DATE '2001-01-01')
);

CREATE TABLE CLIENTES(
    DNI VARCHAR2(10),
    NOMBRE VARCHAR2(30) NOT NULL,
    NACIONALIDAD VARCHAR2(30),
    FECHA_NACIMIENTO DATE,
    DIRECCION VARCHAR2(50),
    CONSTRAINT PK1_CLIENTES PRIMARY KEY (DNI)
);

CREATE TABLE ALQUILERES(
    MATRICULA VARCHAR2(7) NOT NULL,
    DNI VARCHAR2(10) NOT NULL,
    FECHA_HORA DATE,
    NUM_DIAS NUMBER(2) NOT NULL,
    KILOMETROS NUMBER(4) DEFAULT 0,
    CONSTRAINT PK_ALQUILERES PRIMARY KEY (MATRICULA, DNI, FECHA_HORA),
    CONSTRAINT FK_ALQUILERES_VEHICULO FOREIGN KEY (MATRICULA) REFERENCES VEHICULO (MATRICULA),
    CONSTRAINT FK_ALQUILERES_CLIENTES FOREIGN KEY (DNI) REFERENCES CLIENTES (DNI)

);

-- Ejercicio 1
ALTER TABLE CLIENTES  ADD CONSTRAINT CHK_DNI CHECK (REGEXP_LIKE(DNI, '^[0-9]{8}-[A-Z]$'));

ALTER TABLE VEHICULO ADD CONSTRAINT CHK_MATRICULA CHECK (REGEXP_LIKE(MATRICULA, '^[0-9]{4}[A-Z]{3}$'));

-- Ejercicio 2
ALTER TABLE VEHICULO  ADD TOTAL_KILOMETROS NUMBER(10) DEFAULT 0;