CREATE TABLE EQUIPOS(
    COD_EQUIPO VARCHAR2 (4),
    NOMBRE VARCHAR2 (30) NOT NULL,
    LOCALIDAD VARCHAR2 (15),
    CONSTRAINT PK_EQUIPOS PRIMARY KEY (COD_EQUIPO)
);

CREATE TABLE JUGADORES(
    COD_JUGADOR VARCHAR2 (4),
    NOMBRE VARCHAR2 (30) NOT NULL,
    FECHA_NACIMIENTO DATE,
    DEMARCACION VARCHAR2 (10),
    COD_EQUIPO VARCHAR2 (4),
    CONSTRAINT PK_JUGADORES PRIMARY KEY (COD_JUGADOR),
    CONSTRAINT FK_JUGADORES FOREIGN KEY (COD_EQUIPO) REFERENCES EQUIPOS(COD_EQUIPO)
);

CREATE TABLE PARTIDOS(
    COD_PARTIDO VARCHAR2 (4),
    COD_EQUIPO_LOCAL VARCHAR2 (4),
    COD_EQUIPO_VISITANTE VARCHAR2 (4),
    FECHA DATE,
    COMPETICION VARCHAR2 (4),
    JORNADA VARCHAR2 (20),
    CONSTRAINT PK_PARTIDOS PRIMARY KEY (COD_PARTIDO),
    CONSTRAINT FK_PARTIDOS FOREIGN KEY (COD_EQUIPO_LOCAL) REFERENCES EQUIPOS(COD_EQUIPO),
    CONSTRAINT FK2_PARTIDOS FOREIGN KEY (COD_EQUIPO_VISITANTE) REFERENCES EQUIPOS(COD_EQUIPO),
    CONSTRAINT CHK_FECHA CHECK (TO_CHAR(FECHA,'MM') NOT IN ('07','08')),
    CONSTRAINT CHK2_COMPETICION CHECK (COMPETICION IN ('Copa','Liga'))
);

CREATE TABLE INCIDENCIAS(
    NUM_INCIDENCIA VARCHAR2 (6),
    COD_PARTIDO VARCHAR2 (4),
    COD_JUGADOR VARCHAR2 (4),
    MINUTO NUMBER (2),
    TIPO VARCHAR2 (20) NOT NULL,
    CONSTRAINT PK_INCIDENCIAS PRIMARY KEY (NUM_INCIDENCIA),
    CONSTRAINT FK_INCIDENCIAS FOREIGN KEY (COD_PARTIDO) REFERENCES PARTIDOS(COD_PARTIDO),
    CONSTRAINT FK2_INCIDENCIAS FOREIGN KEY (COD_JUGADOR) REFERENCES JUGADORES(COD_JUGADOR),
    CONSTRAINT CHK_MINUTO CHECK (MINUTO >= 1 AND MINUTO <= 100)
);


ALTER TABLE JUGADORES ADD CONSTRAINT CHK_NOMBRE CHECK (REGEXP_LIKE(NOMBRE,'^[A-Z](\\.[A-Z])*$')); --ÎNCICIO EN CADENA. A-Z LA PRIMERA EN MAYUSCULA. /. PARA QUE HAYA UN PUNTO DESPUESS. * CERO O MAS VECES. $ FIN CADENA
ALTER TABLE JUGADORES ADD CONSTRAINT CHK2_DEMARCACION CHECK (DEMARCACION IN ('Portero','Defensa','Medio','Delantero'));

ALTER TABLE EQUIPOS ADD CONSTRAINT CHK_COD_EQUIPO CHECK (REGEXP_LIKE(COD_EQUIPO,'^[0-9].*')); --^iniciio de la cadena, un numero del 0 al 9, el . significa cualquier caracter, * se puede repetir el caacter anterior

ALTER TABLE EQUIPOS ADD (GOLES_MARCADOS NUMBER(3));


