-- 1
SELECT A.NOMBRE, A.COSTEBASICO, A.IDTITULACION
FROM ASIGNATURA A
ORDER BY A.IDTITULACION, A.COSTEBASICO DESC, A.NOMBRE;

SELECT A.NOMBRE, A.COSTEBASICO, A.IDTITULACION
FROM ASIGNATURA A
ORDER BY A.IDTITULACION, A.COSTEBASICO DESC, A.NOMBRE;


--2
SELECT NOMBRE, APELLIDO
FROM PERSONA p, PROFESOR p2 
WHERE P.DNI=P2.DNI;

SELECT NOMBRE, APELLIDO
FROM PERSONA p JOIN PROFESOR p2 
ON P.DNI=P2.DNI;


-- 3
SELECT A.NOMBRE
FROM ASIGNATURA A, PROFESOR PR, PERSONA P
WHERE A.IDPROFESOR = PR.IDPROFESOR
AND PR.DNI = P.DNI
AND UPPER(P.CIUDAD) = 'SEVILLA';

-- 4
SELECT P.NOMBRE, P.APELLIDO
FROM PERSONA P, ALUMNO AL
WHERE P.DNI = AL.DNI;

SELECT P.NOMBRE, P.APELLIDO
FROM PERSONA P
JOIN ALUMNO AL ON P.DNI = AL.DNI;


-- 5
SELECT P.DNI, P.NOMBRE, P.APELLIDO
FROM PERSONA P, ALUMNO AL
WHERE P.DNI = AL.DNI
AND UPPER(P.CIUDAD) = 'SEVILLA';


-- 6
SELECT P.DNI, P.NOMBRE, P.APELLIDO
FROM PERSONA P, ALUMNO AL, ALUMNO_ASIGNATURA AA, ASIGNATURA A
WHERE P.DNI = AL.DNI
AND AL.IDALUMNO = AA.IDALUMNO
AND AA.IDASIGNATURA = A.IDASIGNATURA
AND A.NOMBRE = 'Seguridad Vial';


-- 7
SELECT DISTINCT A.IDTITULACION
FROM ALUMNO AL, ALUMNO_ASIGNATURA AA, ASIGNATURA A
WHERE AL.IDALUMNO = AA.IDALUMNO
AND AA.IDASIGNATURA = A.IDASIGNATURA
AND AL.DNI = '20202020A';


-- 8
SELECT A.NOMBRE
FROM PERSONA P, ALUMNO AL, ALUMNO_ASIGNATURA AA, ASIGNATURA A
WHERE P.DNI = AL.DNI
AND AL.IDALUMNO = AA.IDALUMNO
AND AA.IDASIGNATURA = A.IDASIGNATURA
AND P.NOMBRE = 'ROSA'
AND P.APELLIDO = 'GARCIA';


-- 9
SELECT DISTINCT AL.DNI
FROM PROFESOR PR, PERSONA P, ASIGNATURA A, ALUMNO_ASIGNATURA AA, ALUMNO AL
WHERE PR.DNI = P.DNI
AND PR.IDPROFESOR = A.IDPROFESOR
AND A.IDASIGNATURA = AA.IDASIGNATURA
AND AA.IDALUMNO = AL.IDALUMNO
AND P.NOMBRE = 'JORGE'
AND P.APELLIDO = 'SAENZ';


-- 11
SELECT DISTINCT T.NOMBRE
FROM TITULACION T, ASIGNATURA A
WHERE T.IDTITULACION = A.IDTITULACION
AND A.CREDITOS = 4;
