DROP TABLE IF EXISTS PUBLICACIONES;
DROP TABLE IF EXISTS LIBRO_AUTOR;
ALTER TABLE AUTOR DROP FOREIGN KEY FK_AUTOR;
DROP TABLE IF EXISTS AUTOR;
ALTER TABLE LIBRO DROP FOREIGN KEY FK_LIBRO;
ALTER TABLE LIBRO DROP FOREIGN KEY FK2_LIBRO;
DROP TABLE IF EXISTS LIBRO;
DROP TABLE IF EXISTS EDITORIAL;
ALTER TABLE TEMA DROP FOREIGN KEY FK_TEMA;
DROP TABLE IF EXISTS TEMA;


CREATE TABLE TEMA (
    COD_TEMA INT,
    DENOMINACION VARCHAR(20),
    COD_TEMA_PADRE INT,
    CONSTRAINT PK_TEMA PRIMARY KEY (COD_TEMA),
    CONSTRAINT FK_TEMA FOREIGN KEY (COD_TEMA_PADRE) REFERENCES TEMA(COD_TEMA),
    CONSTRAINT CHK_TEMA_PADRE CHECK (COD_TEMA_PADRE >= COD_TEMA)
);

CREATE TABLE LIBRO (
    COD_LIBRO INT,
    TITULO VARCHAR(10),
    F_CREACION DATE,
    COD_TEMA INT,
    AUTOR_PRINCIPAL INT,
    CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIBRO),
    CONSTRAINT FK_LIBRO FOREIGN KEY (COD_TEMA) REFERENCES TEMA(COD_TEMA)
);

CREATE TABLE AUTOR (
    COD_AUTOR INT,
    NOMBRE VARCHAR(10),
    F_NACIMIENTO DATE,
    LIBRO_PRINCIPAL INT,
    CONSTRAINT PK_AUTOR PRIMARY KEY (COD_AUTOR),
    CONSTRAINT FK_AUTOR FOREIGN KEY (LIBRO_PRINCIPAL) REFERENCES LIBRO(COD_LIBRO)
);

CREATE TABLE LIBRO_AUTOR (
    COD_LIBRO INT,
    COD_AUTOR INT,
    ORDEN INT,
    CONSTRAINT PK_LIBRO_AUTOR PRIMARY KEY (COD_LIBRO, COD_AUTOR),
    CONSTRAINT FK_LIBRO_AUTOR FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
    CONSTRAINT FK2_LIBRO_AUTOR FOREIGN KEY (COD_AUTOR) REFERENCES AUTOR(COD_AUTOR),
    CONSTRAINT CHK_ORDEN CHECK (ORDEN >= 1 AND ORDEN <= 5)
);

CREATE TABLE EDITORIAL (
    COD_EDITORIAL INT,
    DENOMINACION VARCHAR(20),
    CONSTRAINT PK_EDITORIAL PRIMARY KEY (COD_EDITORIAL)
);

CREATE TABLE PUBLICACIONES (
    COD_EDITORIAL INT,
    COD_LIBRO INT,
    PRECIO DECIMAL(10,2) NOT NULL,
    F_PUBLICACION DATE,
    CONSTRAINT PK_PUBLICACIONES PRIMARY KEY (COD_EDITORIAL, COD_LIBRO),
    CONSTRAINT FK_PUBLICACIONES FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
    CONSTRAINT FK2_PUBLICACIONES FOREIGN KEY (COD_EDITORIAL) REFERENCES EDITORIAL(COD_EDITORIAL) ON DELETE CASCADE,
    CONSTRAINT CHK_PRECIO CHECK (PRECIO > 0)
);

ALTER TABLE LIBRO ADD CONSTRAINT FK2_LIBRO FOREIGN KEY (AUTOR_PRINCIPAL) REFERENCES AUTOR(COD_AUTOR);
