-- RESPUESTA 1:
-- Actualmente la clave primaria de PUBLICACIONES es (COD_EDITORIAL, COD_LIBRO).
-- Esto impide que una misma editorial publique varias veces el mismo libro,
-- porque esa combinación solo puede aparecer una vez.
-- Si quisiéramos permitir varias publicaciones del mismo libro por la misma editorial,
-- habría que añadir un campo adicional (por ejemplo, NUM_EDICION o ID_PUBLICACION)
-- y usarlo en la clave primaria junto con COD_EDITORIAL y COD_LIBRO.

-- RESPUESTA 2:
-- Para borrar todas las tablas creadas se utilizan los siguientes comandos:

DROP TABLE PUBLICACIONES CASCADE CONSTRAINTS;
DROP TABLE LIBRO_AUTOR CASCADE CONSTRAINTS;
DROP TABLE LIBRO CASCADE CONSTRAINTS;
DROP TABLE AUTOR CASCADE CONSTRAINTS;
DROP TABLE EDITORIAL CASCADE CONSTRAINTS;
DROP TABLE TEMA CASCADE CONSTRAINTS;

CREATE TABLE TEMA(
    COD_TEMA NUMBER (10),
    DENOMINACION VARCHAR2 (20),
    COD_TEMA_PADRE NUMBER (10),
    CONSTRAINT PK_TEMA PRIMARY KEY (COD_TEMA),
    CONSTRAINT FK_TEMA FOREIGN KEY (COD_TEMA_PADRE) REFERENCES TEMA(COD_TEMA),
    CONSTRAINT CHK_TEMA_PADRE CHECK (COD_TEMA_PADRE >= COD_TEMA)
);

CREATE TABLE LIBRO(
    COD_LIBRO NUMBER (10),
    TITULO VARCHAR2 (10),
    F_CREACION DATE,
    COD_TEMA NUMBER (10),
    AUTOR_PRINCIPAL NUMBER (10),
    CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIBRO),
    CONSTRAINT FK_LIBRO FOREIGN KEY (COD_TEMA) REFERENCES TEMA(COD_TEMA)
);

CREATE TABLE AUTOR(
    COD_AUTOR NUMBER (10),
    NOMBRE VARCHAR2 (10),
    F_NACIMIENTO DATE,
    LIBRO_PRINCIPAL NUMBER (10),
    CONSTRAINT PK_AUTOR PRIMARY KEY (COD_AUTOR),
    CONSTRAINT FK_AUTOR FOREIGN KEY (LIBRO_PRINCIPAL) REFERENCES LIBRO(COD_LIBRO)
);

CREATE TABLE LIBRO_AUTOR(
    COD_LIBRO NUMBER (10),
    COD_AUTOR NUMBER (10),
    ORDEN NUMBER (1),
    CONSTRAINT PK_LIBRO_AUTOR PRIMARY KEY (COD_LIBRO, COD_AUTOR),
    CONSTRAINT FK_LIBRO_AUTOR FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
    CONSTRAINT FK2_LIBRO_AUTOR FOREIGN KEY (COD_AUTOR) REFERENCES AUTOR(COD_AUTOR),
    CONSTRAINT CHK_ORDEN CHECK (ORDEN >= 1 AND ORDEN <= 5)
);

CREATE TABLE EDITORIAL(
    COD_EDITORIAL NUMBER (10),
    DENOMINACION VARCHAR2 (20),
    CONSTRAINT PK_EDITORIAL PRIMARY KEY (COD_EDITORIAL)
);

CREATE TABLE PUBLICACIONES(
    COD_EDITORIAL NUMBER (10),
    COD_LIBRO NUMBER (10),
    PRECIO NUMBER (10,2) NOT NULL,
    F_PUBLICACION DATE DEFAULT SYSDATE,
    CONSTRAINT PK_PUBLICACIONES PRIMARY KEY (COD_EDITORIAL, COD_LIBRO),
    CONSTRAINT FK_PUBLICACIONES FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
    CONSTRAINT FK2_PUBLICACIONES FOREIGN KEY (COD_EDITORIAL) REFERENCES EDITORIAL(COD_EDITORIAL) ON DELETE CASCADE,
    CONSTRAINT CHK_PRECIO CHECK (PRECIO > 0)
);

ALTER TABLE LIBRO ADD CONSTRAINT FK2_LIBRO FOREIGN KEY (AUTOR_PRINCIPAL) REFERENCES AUTOR(COD_AUTOR);