-- Crear todas las tablas
CREATE TABLE CLIENTE(
    COD_CLIENTE NUMBER(10),
    EMAIL VARCHAR2(50),
    NOMBRE VARCHAR2(30),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE)
);

CREATE TABLE PRODUCTO(
    COD_PRODUCTO NUMBER(10),
    NOMBRE VARCHAR2(30),
    PRECIO NUMBER(10,2),
    STOCK NUMBER(10),
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (COD_PRODUCTO),
    CONSTRAINT CHK_PRECIO CHECK (PRECIO > 0),
    CONSTRAINT CHK_STOCK CHECK (STOCK >= 0)
);

CREATE TABLE PEDIDO(
    COD_PEDIDO NUMBER(10),
    COD_CLIENTE NUMBER(10),
    FECHA DATE DEFAULT SYSDATE,
    CONSTRAINT PK_PEDIDO PRIMARY KEY (COD_PEDIDO),
    CONSTRAINT FK_PEDIDO_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE(COD_CLIENTE)
);

CREATE TABLE LINEA_PEDIDO(
    COD_PEDIDO NUMBER(10),
    COD_PRODUCTO NUMBER(10),
    CANTIDAD NUMBER(10),
    CONSTRAINT PK_LINEA PRIMARY KEY (COD_PEDIDO, COD_PRODUCTO),
    CONSTRAINT FK_LP_PEDIDO FOREIGN KEY (COD_PEDIDO) REFERENCES PEDIDO(COD_PEDIDO),
    CONSTRAINT FK_LP_PRODUCTO FOREIGN KEY (COD_PRODUCTO) REFERENCES PRODUCTO(COD_PRODUCTO)
);

-- Crear un índice sobre email
CREATE INDEX IDX_CLIENTE_EMAIL ON CLIENTE(EMAIL);

-- Crear una vista con pedidos y total del pedido
CREATE OR REPLACE VIEW PEDIDOS_TOTALES AS
-- SELECT P.COD_PEDIDO,
       P.COD_CLIENTE,
       P.FECHA,
       SUM(L.CANTIDAD * PR.PRECIO) AS TOTAL
FROM PEDIDO P
JOIN LINEA_PEDIDO L ON P.COD_PEDIDO = L.COD_PEDIDO
JOIN PRODUCTO PR ON L.COD_PRODUCTO = PR.COD_PRODUCTO
GROUP BY P.COD_PEDIDO, P.COD_CLIENTE, P.FECHA;


-- DDL + TRANSACCIONES
-- Insertar clientes y productos
INSERT INTO CLIENTE VALUES (1, 'joel@mail.com', 'Joel');
INSERT INTO CLIENTE VALUES (2, 'maria@mail.com', 'Maria');

INSERT INTO PRODUCTO VALUES (1, 'Teclado', 20, 50);
INSERT INTO PRODUCTO VALUES (2, 'Raton', 15, 100);
INSERT INTO PRODUCTO VALUES (3, 'Monitor', 150, 20);

-- Crear un SAVEPOINT pedido1
SAVEPOINT pedido1;

-- Crear un pedido y sus líneas
INSERT INTO PEDIDO (COD_PEDIDO, COD_CLIENTE) VALUES (1, 1);
INSERT INTO LINEA_PEDIDO VALUES (1, 1, 2);
INSERT INTO LINEA_PEDIDO VALUES (1, 2, 1);

-- Reducir stock incorrectamente
UPDATE PRODUCTO SET STOCK = -10 WHERE COD_PRODUCTO = 1;

-- Recuperar los datos
ROLLBACK TO pedido1;

-- Corregir el stock
UPDATE PRODUCTO SET STOCK = 48 WHERE COD_PRODUCTO = 1;

-- Confirmar la transacción
COMMIT;

-- SELECT * FROM CLIENTE;
-- SELECT * FROM PRODUCTO;
-- SELECT * FROM PEDIDO;
-- SELECT * FROM LINEA_PEDIDO;
-- SELECT * FROM PEDIDOS_TOTALES;
