CREATE TABLE BIBLIOTECARIO(
    COD_BIBLIOTECARIO INT,
    NOMBRE VARCHAR(20),
    TURNO VARCHAR(10),
    COD_JEFE INT UNIQUE,
    CONSTRAINT PK_BIBLIOTECARIO PRIMARY KEY (COD_BIBLIOTECARIO),
    CONSTRAINT FK_BIBLIOTECARIO FOREIGN KEY (COD_JEFE) REFERENCES BIBLIOTECARIO(COD_JEFE)
);

CREATE TABLE LECTOR(
    COD_LECTOR INT,
    DNI VARCHAR(9),
    NOMBRE VARCHAR(20),
    SEXO VARCHAR(1),
    CONSTRAINT PK_LECTOR PRIMARY KEY (COD_LECTOR)
);

CREATE TABLE LIBRO(
    COD_LIBRO INT,
    TITULO VARCHAR(10),
    NUM_PAGINAS INT,
    CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIBRO)
);

CREATE TABLE PRESTAMO(
    COD_PRESTAMO INT,
    COD_LECTOR INT,
    COD_LIBRO INT,
    FECHA_PRESTAMO DATE,
    FECHA_DEVOLUCION DATE,
    CONSTRAINT PK_PRESTAMO PRIMARY KEY (COD_PRESTAMO),
    CONSTRAINT FK_PRESTAMO FOREIGN KEY (COD_LECTOR) REFERENCES LECTOR (COD_LECTOR),
    CONSTRAINT FK2_PRESTAMO FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO (COD_LIBRO)
);

CREATE TABLE ATENCION(
    COD_BIBLIOTECARIO INT,
    COD_LECTOR INT,
    FECHA DATE,
    OBSERVACIONES VARCHAR(10),
    CONSTRAINT PK_ATENCION PRIMARY KEY (COD_BIBLIOTECARIO, COD_LECTOR),
    CONSTRAINT FK_ATENCION FOREIGN KEY (COD_BIBLIOTECARIO) REFERENCES BIBLIOTECARIO (COD_BIBLIOTECARIO),
    CONSTRAINT FK2_ATENCION FOREIGN KEY(COD_LECTOR) REFERENCES LECTOR (COD_LECTOR)
);



-- APARTADO 1 

-- LA FECHA DE PRÉSTAMO TENDRÁ COMO VALOR POR DEFECTO LA FECHA ACTUAL
ALTER TABLE PRESTAMO MODIFY FECHA_PRESTAMO DATE DEFAULT (CURRENT_DATE);


-- EL NÚMERO DE PÁGINAS DE UN LIBRO DEBE SER MAYOR QUE 10
ALTER TABLE LIBRO ADD CONSTRAINT CK_LIBRO_NUM_PAGINAS CHECK (NUM_PAGINAS > 10);


-- LA FECHA DE DEVOLUCIÓN PUEDE SER NULA, PERO SI TIENE VALOR SERÁ MAYOR QUE LA FECHA DE PRÉSTAMO
ALTER TABLE PRESTAMO ADD CONSTRAINT CK_PRESTAMO_FECHAS CHECK (FECHA_DEVOLUCION IS NULL OR FECHA_DEVOLUCION > FECHA_PRESTAMO);


-- EL TURNO DEL BIBLIOTECARIO SERÁ POR DEFECTO 'MAÑANA'
ALTER TABLE BIBLIOTECARIO MODIFY TURNO DEFAULT 'MAÑANA';


-- NO SE PODRÁ BORRAR UN LIBRO SI EXISTE ALGÚN PRÉSTAMO ASOCIADO
ALTER TABLE PRESTAMO DROP FOREIGN KEY FK2_PRESTAMO;

ALTER TABLE PRESTAMO ADD CONSTRAINT FK2_PRESTAMO FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO (COD_LIBRO);


-- AL BORRAR UN BIBLIOTECARIO, LOS QUE DEPENDÍAN DE ÉL QUEDARÁN CON JEFE A NULL
ALTER TABLE BIBLIOTECARIO DROP FOREIGN KEY FK_BIBLIOTECARIO;

ALTER TABLE BIBLIOTECARIO ADD CONSTRAINT FK_BIBLIOTECARIO FOREIGN KEY (COD_JEFE) REFERENCES BIBLIOTECARIO (COD_BIBLIOTECARIO) ON DELETE SET NULL;


-- AL BORRAR UN BIBLIOTECARIO SE BORRARÁN TODAS LAS ATENCIONES ASOCIADAS
ALTER TABLE ATENCION DROP FOREIGN KEY FK_ATENCION;

ALTER TABLE ATENCION ADD CONSTRAINT FK_ATENCION FOREIGN KEY (COD_BIBLIOTECARIO) REFERENCES BIBLIOTECARIO (COD_BIBLIOTECARIO) ON DELETE CASCADE;


-- AL BORRAR UN LECTOR SE BORRARÁN TODOS LOS PRÉSTAMOS Y ATENCIONES ASOCIADOS
ALTER TABLE PRESTAMO DROP FOREIGN KEY FK_PRESTAMO;

ALTER TABLE PRESTAMO ADD CONSTRAINT FK_PRESTAMO FOREIGN KEY (COD_LECTOR) REFERENCES LECTOR (COD_LECTOR) ON DELETE CASCADE;

ALTER TABLE ATENCION DROP FOREIGN KEY FK2_ATENCION;

ALTER TABLE ATENCION ADD CONSTRAINT FK2_ATENCION FOREIGN KEY (COD_LECTOR) REFERENCES LECTOR (COD_LECTOR) ON DELETE CASCADE;


-- APARTADO 2

-- EL CAMPO SEXO SOLO PODRÁ TOMAR LOS VALORES 'H' O 'M'
ALTER TABLE LECTOR ADD CONSTRAINT CK_SEXO CHECK (SEXO IN ('H','M'));

-- EXPLICA POR QUÉ UN BIBLIOTECARIO NO PUEDE ATENDER DOS VECES AL MISMO LECTOR Y ARRÉGLALO
-- POR EL APARTADO "CONSTRAINT PK_ATENCION PRIMARY KEY (COD_BIBLIOTECARIO, COD_LECTOR)"
ALTER TABLE ATENCION DROP CONSTRAINT PK_ATENCION;

ALTER TABLE ATENCION ADD COD_ATENCION INT;

ALTER TABLE ATENCION ADD CONSTRAINT PK_ATENCION PRIMARY KEY (COD_ATENCION);


-- MODIFICAR LA LONGITUD DEL DNI A 12
ALTER TABLE LECTOR MODIFY DNI VARCHAR2(12);


-- INSERTAR UN BIBLIOTECARIO CON CÓDIGO 1 Y DOS LECTORES CON CÓDIGO 1 Y 2
INSERT INTO BIBLIOTECARIO (COD_BIBLIOTECARIO, NOMBRE, TURNO, COD_JEFE) VALUES (1, 'PEPE', DEFAULT, NULL);

INSERT INTO LECTOR (COD_LECTOR, DNI, NOMBRE, SEXO) VALUES (1, '11111111A', 'JUAN', 'H');

INSERT INTO LECTOR (COD_LECTOR, DNI, NOMBRE, SEXO) VALUES (2, '22222222B', 'MARIA', 'M');


-- INSERTAR UN LIBRO CON CÓDIGO 1 Y 120 PÁGINAS
INSERT INTO LIBRO (COD_LIBRO, TITULO, NUM_PAGINAS) VALUES (1, 'LIBRO1', 120);


-- EL LECTOR 1 PIDE PRESTADO EL LIBRO 1 HOY
INSERT INTO PRESTAMO (COD_PRESTAMO, COD_LECTOR, COD_LIBRO) VALUES (1, 1, 1);


-- EL BIBLIOTECARIO 1 ATIENDE AL LECTOR 1 HOY
INSERT INTO ATENCION (COD_ATENCION, COD_BIBLIOTECARIO, COD_LECTOR, FECHA) VALUES (1, 1, 1, DEFAULT (CURRENT_DATE);


-- AÑADIR EL CAMPO FECHA_PROXIMA_VISITA A ATENCION
ALTER TABLE ATENCION ADD FECHA_PROXIMA_VISITA DATE;


-- MODIFICAR EL NOMBRE DEL LECTOR 1 A 'ANA GARCÍA' Y SEXO 'M'
UPDATE LECTOR
SET NOMBRE = 'ANA GARCÍA', SEXO = 'M'
WHERE COD_LECTOR = 1;


-- BORRAR TODOS LOS DATOS DEL LECTOR 1 CON UNA SOLA INSTRUCCIÓN
DELETE FROM LECTOR WHERE COD_LECTOR = 1;


-- BORRAR TODAS LAS TABLAS CREADAS
DROP TABLE ATENCION;
DROP TABLE PRESTAMO;
DROP TABLE LIBRO;
DROP TABLE LECTOR;
DROP TABLE BIBLIOTECARIO;

