CREATE TABLE PROFESORES(
    NOMBRE VARCHAR(30),
    APELLIDO1 VARCHAR(30),
    APELLIDO2 VARCHAR(30),
    DNI INT,
    DIRECCION VARCHAR(50),
    TITULO VARCHAR(40),
    GANA INT,
    CONSTRAINT PK_PROFESORES PRIMARY KEY(DNI)
);

CREATE TABLE CURSOS(
    NOMBRE_CURSO VARCHAR(40),
    COD_CURSO INT,
    DNI_PROFESOR INT,
    MAXIMO_ALUMNOS INT,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    NUM_HORAS INT,
    CONSTRAINT PK_CURSOS PRIMARY KEY(COD_CURSO),
    CONSTRAINT FK_CURSOS_PROF FOREIGN KEY(DNI_PROFESOR) REFERENCES PROFESORES(DNI)
);

CREATE TABLE ALUMNOS(
    NOMBRE VARCHAR(30),
    APELLIDO1 VARCHAR(30),
    APELLIDO2 VARCHAR(30),
    DNI INT,
    DIRECCION VARCHAR(50),
    SEXO VARCHAR(1),
    FECHA_NACIMIENTO DATE,
    CURSO INT,
    CONSTRAINT PK_ALUMNOS PRIMARY KEY(DNI),
    CONSTRAINT FK_ALUMNOS_CURSO FOREIGN KEY(CURSO) REFERENCES CURSOS(COD_CURSO),
    CONSTRAINT CHK_ALUMNOS_SEXO CHECK(SEXO IN('H','M'))
);


INSERT INTO PROFESORES VALUES('Juan','Arch','López',32432455,'Puerta Negra, 4','Ing. Informática',7500);
INSERT INTO PROFESORES VALUES('María','Oliva','Rubio',43215643,'Juan Alfonso 32','Lda. Fil. Inglesa',5400);

INSERT INTO CURSOS VALUES('Inglés Básico',1,43215643,15,'2000-11-01','2000-12-22',120);
INSERT INTO CURSOS VALUES('Administración Linux',2,32432455,NULL,'2000-09-01',NULL,80);

INSERT INTO ALUMNOS VALUES('Lucas','Manilva','López',123523,'Alhamar, 3','H','1979-11-01',1);
INSERT INTO ALUMNOS VALUES('Antonia','López','Alcantara',2567567,'Maniquí, 21','M',NULL,2);
INSERT INTO ALUMNOS VALUES('Manuel','Alcantara','Pedrós',3123689,'Julian, 2','H',NULL,1);


-- ERROR: curso 3 no existe
INSERT INTO ALUMNOS VALUES('José','Pérez','Caballar',4896765,'Jarcha,5','H','1977-02-03',3);

-- 3. INSERT ERRÓNEO (SEXO = P)
INSERT INTO ALUMNOS VALUES('Sergio','Navas','Retal',123523,NULL,'P',NULL,1);

-- 4. INSERT ERRÓNEO (PK DUPLICADA)
INSERT INTO PROFESORES VALUES('Juan','Arch','López',32432455,'Puerta Negra, 4','Ing. Informática',NULL);

-- 5. INSERT ALUMNA SIN CURSO
INSERT INTO ALUMNOS(NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO,FECHA_NACIMIENTO)
VALUES('María','Jaén','Sevilla',789678,'Martos, 5','M',NULL);

-- 6. CORREGIR FECHA DE ANTONIA
UPDATE ALUMNOS SET FECHA_NACIMIENTO='1976-12-23'
WHERE NOMBRE='Antonia' AND APELLIDO1='López';

-- 7. CAMBIAR CURSO A 5 (ERROR: NO EXISTE)
UPDATE ALUMNOS SET CURSO=5
WHERE NOMBRE='Antonia' AND APELLIDO1='López';

-- 8. ELIMINAR PROFESORA INEXISTENTE
DELETE FROM PROFESORES WHERE NOMBRE='Laura' AND APELLIDO1='Jiménez';

-- 9. BORRAR CURSO 1 (ERROR: TIENE ALUMNOS)
DELETE FROM CURSOS WHERE COD_CURSO=1;

-- 10. AÑADIR CAMPO
ALTER TABLE CURSOS ADD NUMERO_ALUMNOS INT;

-- 11. FECHA POR DEFECTO A NULOS
UPDATE ALUMNOS SET FECHA_NACIMIENTO='2012-01-01'
WHERE FECHA_NACIMIENTO IS NULL;

-- 12. BORRAR CAMPO SEXO
ALTER TABLE ALUMNOS DROP COLUMN SEXO;

-- 13. SUBIR 20% A INFORMÁTICA
UPDATE PROFESORES SET GANA=GANA*1.20
WHERE TITULO LIKE '%Informática%';

-- 14. CAMBIAR DNI DE JUAN ARCH
UPDATE PROFESORES SET DNI=1234567
WHERE NOMBRE='Juan' AND APELLIDO1='Arch';

-- 15. CAMBIAR DNI A TODOS LOS INFORMÁTICOS (ERROR SI HAY MÁS DE UNO)
UPDATE PROFESORES SET DNI=7654321
WHERE TITULO LIKE '%Informática%';

-- 16. CAMBIAR SEXO DE MARÍA JAÉN (ERROR: COLUMNA YA BORRADA)
UPDATE ALUMNOS SET SEXO='F'
WHERE NOMBRE='María' AND APELLIDO1='Jaén';


-- ADICIONALES MOODLE
CREATE TABLE DEPARTAMENTOS(
    CODIGO INT AUTO_INCREMENT,
    DESCRIPCION VARCHAR(100),
    CONSTRAINT PK_DEPARTAMENTOS PRIMARY KEY(CODIGO)
);

INSERT INTO DEPARTAMENTOS(DESCRIPCION) VALUES('Contabilidad');
INSERT INTO DEPARTAMENTOS(DESCRIPCION) VALUES('Marketing');
INSERT INTO DEPARTAMENTOS(DESCRIPCION) VALUES('Recursos Humanos');
INSERT INTO DEPARTAMENTOS(DESCRIPCION) VALUES('Informática');

