ALTER TABLE ENFERMO ADD CONSTRAINT CHK_SEXO CHECK (SEXO IN ('H','M'));

ALTER TABLE ENFERMO MODIFY NSS VARCHAR2(22);

ALTER TABLE VISITA ADD FECHA_PROXIMA_VISITA DATE;

ALTER TABLE VISITA DROP CONSTRAINT PK_VISITA;
ALTER TABLE VISITA ADD CONSTRAINT PK_VISITA PRIMARY KEY (COD_MEDICO, COD_INSCRIPCION, FECHA);

DELETE FROM ENFERMO;

DROP TABLE VISITA CASCADE CONSTRAINTS;
DROP TABLE INGRESO CASCADE CONSTRAINTS;
DROP TABLE MEDICO CASCADE CONSTRAINTS;
DROP TABLE ENFERMO CASCADE CONSTRAINTS;
DROP TABLE HABITACION CASCADE CONSTRAINTS;

