CREATE TABLE CLIENTE(
    COD_CLIENTE NUMBER (10),
    NOMBRE VARCHAR2 (15),
    CALLE VARCHAR2 (15),
    NUMERO NUMBER (10),
    COMUNA VARCHAR2 (20),
    CIUDAD VARCHAR2 (10)
);

CREATE TABLE TELEFONO(
    NUMERO NUMBER (9)
);

CREATE TABLE ASOCIADO(
    COD_CLIENTE NUMBER (10),
    NUM_TELEFONO NUMBER (9)
);


CREATE TABLE VENTA(
    ID_VENTA NUMBER (10),
    MONTO_TOTAL NUMBER (10),
    COD_CLIENTE NUMBER (10)
);

CREATE TABLE CATEGORIA(
    ID_CATEGORIA NUMBER (10),
    NOMBRE VARCHAR2 (15),
    DESCRIPCION VARCHAR2 (40)
);

CREATE TABLE PROVEEDOR(
    COD_PROVEEDOR NUMBER (10),
    NOMBRE VARCHAR2 (15),
    DIRECCION VARCHAR2 (100),
    TELEFONO NUMBER (9),
    WEB VARCHAR2 (30)
);

CREATE TABLE PRODUCTO(
    ID_PRODUCTO NUMBER (10),
    NOMBRE VARCHAR2 (15),
    PRECIO NUMBER (10,2),
    STOCK NUMBER (5),
    ID_CATEGORIA NUMBER (10),
    ID_PROVEEDOR NUMBER (10)
);

CREATE TABLE INCLUYE(
    ID_VENTA NUMBER (10),
    ID_PRODUCTO NUMBER (10),
    CANTIDAD NUMBER (10),
    PRECIO_VENTA NUMBER (10,2)
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE);

ALTER TABLE TELEFONO ADD CONSTRAINT PK_TELEFONO PRIMARY KEY (NUMERO);

ALTER TABLE ASOCIADO ADD CONSTRAINT PK_ASOCIADO PRIMARY KEY (COD_CLIENTE, NUM_TELEFONO);
ALTER TABLE ASOCIADO ADD CONSTRAINT FK_ASOCIADO FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE);
ALTER TABLE ASOCIADO ADD CONSTRAINT FK2_ASOCIADO FOREIGN KEY (NUM_TELEFONO) REFERENCES TELEFONO (NUMERO);

ALTER TABLE VENTA ADD CONSTRAINT PK_VENTA PRIMARY KEY (ID_VENTA);
ALTER TABLE VENTA ADD CONSTRAINT FK_VENTA FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE);

ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (ID_CATEGORIA);

ALTER TABLE PROVEEDOR ADD CONSTRAINT PK_PROVEEDOR PRIMARY KEY (COD_PROVEEDOR);

ALTER TABLE PRODUCTO ADD CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_PRODUCTO);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PRODUCTO FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA (ID_CATEGORIA);
ALTER TABLE PRODUCTO ADD CONSTRAINT FK2_PRODUCTO FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR (COD_PROVEEDOR);

ALTER TABLE INCLUYE ADD CONSTRAINT PK_INCLUYE PRIMARY KEY (ID_VENTA, ID_PRODUCTO);
ALTER TABLE INCLUYE ADD CONSTRAINT FK_INCLUYE FOREIGN KEY (ID_VENTA) REFERENCES VENTA (ID_VENTA);
ALTER TABLE INCLUYE ADD CONSTRAINT FK2_INCLUYE FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO (ID_PRODUCTO);

