CREATE TABLE CLIENTE
(
    NIF VARCHAR(10),
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20),
    CONSTRAINT PK_CLIENTE PRIMARY KEY (NIF)
);

CREATE TABLE MODELODORMITORIO
(
    COD VARCHAR(10),
    CONSTRAINT PK_MODELODORMITORIO PRIMARY KEY (COD)
);

CREATE TABLE MONTADOR
(
    NIF VARCHAR(10),
    NOMBRE VARCHAR(100),
    DIRECCION VARCHAR(255),
    TELEFONO VARCHAR(20),
    CONSTRAINT PK_MONTADOR PRIMARY KEY (NIF)
);

CREATE TABLE COMPRA
(
    NIF_C VARCHAR(10),
    MODELO VARCHAR(10),
    FECHACOMPRA DATE,
    CONSTRAINT PK_COMPRA PRIMARY KEY (NIF_C, MODELO, FECHACOMPRA),
    CONSTRAINT FK1_COMPRA FOREIGN KEY (NIF_C)
        REFERENCES CLIENTE(NIF),
    CONSTRAINT FK2_COMPRA FOREIGN KEY (MODELO)
        REFERENCES MODELODORMITORIO(COD)
);

CREATE TABLE MONTA
(
    MODELO VARCHAR(10),
    NIF_M VARCHAR(10),
    FECHAMONTAJE DATE,
    CONSTRAINT PK_MONTA PRIMARY KEY (MODELO, NIF_M, FECHAMONTAJE),
    CONSTRAINT FK1_MONTA FOREIGN KEY (MODELO)
        REFERENCES MODELODORMITORIO(COD),
    CONSTRAINT FK2_MONTA FOREIGN KEY (NIF_M)
        REFERENCES MONTADOR(NIF)
);